# Raw Data Preprocessing

# 1. Imports

In [1]:
import pandas as pd
import plotly.express as px
import numpy as np
from scipy.stats import f_oneway

# 2. Raw Data Import

In [2]:
data_2023 = "../data/raw/SUAC_2023.csv"
data_2024 = "../data/raw/SUAC_2024.csv"
data_2025 = "../data/raw/SUAC_2025.csv"
data_2026 = "../data/raw/SUAC_2026.csv"

In [3]:
df_2023 = pd.read_csv(data_2023)
df_2024 = pd.read_csv(data_2024)
df_2025 = pd.read_csv(data_2025)
df_2026 = pd.read_csv(data_2026)

/var/folders/t1/6m61dml920j5z0dm3z5bskw80000gn/T/ipykernel_3234/3567484953.py:1: DtypeWarning: Columns (0: codigo_postal_solicitud) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2023 = pd.read_csv(data_2023)
/var/folders/t1/6m61dml920j5z0dm3z5bskw80000gn/T/ipykernel_3234/3567484953.py:2: DtypeWarning: Columns (0: codigo_postal_solicitud) have mixed types. Specify dtype option on import or set low_memory=False.
  df_2024 = pd.read_csv(data_2024)

# 3. Initial Exploration

In [4]:
df_2023.head()

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,edad,colonia_solicitud,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,latitud,longitud
0,1751404,2023-01-11,10:35:26.541,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Autoridad Responsable,NaN,NaN,NaN
1,1752021,2023-01-11,12:45:18.413,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
2,1752656,2023-01-11,14:59:29.499,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
3,1752838,2023-01-11,16:39:57.5,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
4,1752915,2023-01-11,17:38:06.237,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7710.0,Cerrado,2023-01-18,NaN,NaN

In [5]:
df_2024.head()

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,edad,colonia_solicitud,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,latitud,longitud
0,2547339,2024-04-19,21:16:24,App CDMX,DESAZOLVE,No especificado,NaN,SAN PEDRO EL CHICO,5.0,07480,Cerrado,2024-06-06,19.471184,-99.100071
1,2547340,2024-04-19,21:20:08,Operador Telefónico LOCATEL,RETIRO AMBULANTE,No especificado,NaN,NaN,NaN,04360,Cerrado,2024-05-20,NaN,NaN
2,2547341,2024-04-19,21:20:45,App CDMX,PODA,No especificado,NaN,NaN,NaN,NaN,Cerrado,2024-04-22,NaN,NaN
3,2547342,2024-04-19,21:21:06,App CDMX,SOLICITUD DE VIGILANCIA POLICIACA,No especificado,NaN,NaN,NaN,09500,Cerrado,2024-05-02,NaN,NaN
4,2547344,2024-04-19,21:27:55,App CDMX,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,NaN,EUZKADI,2.0,02660,Cerrado,2024-05-05,19.480044,-99.157328

In [6]:
df_2025.head()

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,edad,colonia_solicitud,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,latitud,longitud
0,3007414,2025-01-07,14:25:47,App CDMX,MANTENIMIENTO VÍA PÚBLICA,No especificado,NaN,NaN,NaN,NaN,Cerrado,2025-01-29,NaN,NaN
1,3000375,2025-01-01,00:16:01,App CDMX,SOLICITUD DE VIGILANCIA POLICIACA,No especificado,NaN,NaN,NaN,01160,Cerrado,2025-01-03,NaN,NaN
2,3008130,2025-01-08,08:00:55,App CDMX,OTRO,No especificado,NaN,NaN,NaN,NaN,Cerrado,2025-02-27,NaN,NaN
3,3000497,2025-01-01,16:13:58,App CDMX,MANTENIMIENTO PARQUE / ÁREA VERDE,No especificado,NaN,TLALPAN CENTRO,12.0,14000,Cerrado,2025-01-07,19.291450,-99.168547
4,3000498,2025-01-01,16:21:54,App CDMX,VERIFICACIÓN ADMINISTRATIVA,No especificado,NaN,CONSTITUCION DE 1917,7.0,09260,Cerrado,2025-01-06,19.352837,-99.058975

In [7]:
df_2026.head()

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,edad,colonia_solicitud,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,latitud,longitud
0,3841679,2026-01-01,07:15:46,App CDMX,FUGA DE AGUA,No especificado,NaN,NaN,NaN,09858,Atendido,2026-01-20,NaN,NaN
1,3841683,2026-01-01,07:39:01,Interoperabilidad SACMEX,FUGA DE AGUA,No especificado,NaN,SAN JUAN CERRO,7.0,9858,Atendido,2026-01-20,19.345325,-99.081876
2,3841684,2026-01-01,07:42:01.448,Portal Ciudadano SUAC,OTRO,Femenino,NaN,LAS CRUCES,8.0,10330,Atendido,2026-01-20,19.320363,-99.258278
3,3841686,2026-01-01,07:46:17,App CDMX,QUEJA DE TRANSPORTE PÚBLICO,No especificado,NaN,NaN,NaN,14376,Atendido,2026-01-06,NaN,NaN
4,3841687,2026-01-01,07:46:37,App CDMX,SOLICITUD DE VIGILANCIA POLICIACA,No especificado,NaN,NaN,NaN,09705,Atendido,2026-01-05,NaN,NaN

## 3.1 Consistency Validation

In [8]:
dfs = {
    2023: df_2023,
    2024: df_2024,
    2025: df_2025,
    2026: df_2026,
}

def explore_dfs(df, name=""):
    print("=" * 70)
    print(f"  INITIAL EXPLORATION — {name}")
    print("=" * 70)

    print(f"\nDimensions: {df.shape[0]} rows × {df.shape[1]} columns\n")

    print("--- info() ---")
    df.info()

In [9]:
for year, df in dfs.items():
    explore_dfs(df, name=f"Year {year}")

======================================================================
  INITIAL EXPLORATION — Year 2023
======================================================================

Dimensions: 565558 rows × 14 columns

--- info() ---
<class 'pandas.DataFrame'>
RangeIndex: 565558 entries, 0 to 565557
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id_folio                 565558 non-null  int64
 1   fecha_solicitud          565558 non-null  str
 2   hora_solicitud           565558 non-null  str
 3   tipo_de_entrada          565558 non-null  str
 4   tema_solicitud           565558 non-null  str
 5   sexo                     347177 non-null  str
 6   edad                     51857 non-null   float64
 7   colonia_solicitud        265184 non-null  str
 8   alcaldia_solicitud       265184 non-null  float64
 9   codigo_postal_solicitud  516043 non-null  object
 10  estatus                  565558 non-null  str
 11  fecha_concluido          561114 non-null  str
 12  latitud                  228154 non-null  float64
 13  longitud                 206204 non-null  float64
dtypes: float64(4), int64(1), object(1), str(8)
memory usage: 109.8+ MB
======================================================================
  INITIAL EXPLORATION — Year 2024
======================================================================

Dimensions: 631916 rows × 14 columns

--- info() ---
<class 'pandas.DataFrame'>
RangeIndex: 631916 entries, 0 to 631915
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id_folio                 631916 non-null  int64
 1   fecha_solicitud          631916 non-null  str
 2   hora_solicitud           631916 non-null  str
 3   tipo_de_entrada          631916 non-null  str
 4   tema_solicitud           631916 non-null  str
 5   sexo                     617903 non-null  str
 6   edad                     85418 non-null   float64
 7   colonia_solicitud        328366 non-null  str
 8   alcaldia_solicitud       328366 non-null  float64
 9   codigo_postal_solicitud  600184 non-null  object
 10  estatus                  631916 non-null  str
 11  fecha_concluido          627189 non-null  str
 12  latitud                  234318 non-null  float64
 13  longitud                 207857 non-null  float64
dtypes: float64(4), int64(1), object(1), str(8)
memory usage: 123.9+ MB
======================================================================
  INITIAL EXPLORATION — Year 2025
======================================================================

Dimensions: 816437 rows × 14 columns

--- info() ---
<class 'pandas.DataFrame'>
RangeIndex: 816437 entries, 0 to 816436
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id_folio                 816437 non-null  int64
 1   fecha_solicitud          816437 non-null  str
 2   hora_solicitud           816437 non-null  str
 3   tipo_de_entrada          816437 non-null  str
 4   tema_solicitud           816437 non-null  str
 5   sexo                     801183 non-null  str
 6   edad                     126538 non-null  float64
 7   colonia_solicitud        411388 non-null  str
 8   alcaldia_solicitud       411388 non-null  float64
 9   codigo_postal_solicitud  804927 non-null  str
 10  estatus                  816437 non-null  str
 11  fecha_concluido          784311 non-null  str
 12  latitud                  382247 non-null  float64
 13  longitud                 357671 non-null  float64
dtypes: float64(4), int64(1), str(9)
memory usage: 166.1 MB
======================================================================
  INITIAL EXPLORATION — Year 2026
======================================================================

Dimensions: 289265 rows × 14 columns

--- info() ---
<class 'pandas.DataFrame'>
RangeIndex: 289265 entries, 0 to 289264
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id_folio                 289265 non-null  int64
 1   fecha_solicitud          289265 non-null  str
 2   hora_solicitud           289265 non-null  str
 3   tipo_de_entrada          289265 non-null  str
 4   tema_solicitud           289265 non-null  str
 5   sexo                     284190 non-null  str
 6   edad                     26002 non-null   float64
 7   colonia_solicitud        149655 non-null  str
 8   alcaldia_solicitud       149655 non-null  float64
 9   codigo_postal_solicitud  286495 non-null  str
 10  estatus                  289265 non-null  str
 11  fecha_concluido          190190 non-null  str
 12  latitud                  142439 non-null  float64
 13  longitud                 133870 non-null  float64
dtypes: float64(4), int64(1), str(9)
memory usage: 59.2 MB

## 3.2 DataFrame Concatenation

In [10]:
list_df = [df_2023,df_2024,df_2025,df_2026]
for df in list_df:
    df['codigo_postal_solicitud'] = df['codigo_postal_solicitud'].astype(str)

In [11]:
df_complete = pd.concat(list_df, ignore_index=True)

## 3.3 Final DataFrame Exploration

In [12]:
df_complete.head()

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,edad,colonia_solicitud,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,latitud,longitud
0,1751404,2023-01-11,10:35:26.541,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Autoridad Responsable,NaN,NaN,NaN
1,1752021,2023-01-11,12:45:18.413,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
2,1752656,2023-01-11,14:59:29.499,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
3,1752838,2023-01-11,16:39:57.5,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
4,1752915,2023-01-11,17:38:06.237,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7710.0,Cerrado,2023-01-18,NaN,NaN

In [13]:
df_complete.shape

(2303176, 14)

In [14]:
df_complete.describe()

,id_folio,edad,alcaldia_solicitud,latitud,longitud
count,2.303176e+06,2.898150e+05,1.154593e+06,987158.000000,905602.000000
mean,2.946632e+06,3.501398e+03,8.550033e+00,18.582701,-99.123430
std,6.923618e+05,1.857546e+06,4.064176e+00,3.862915,0.922771
min,1.739063e+06,0.000000e+00,2.000000e+00,-43.708360,-165.893111
25%,2.348458e+06,4.000000e+01,6.000000e+00,19.315477,-99.174385
50%,2.951948e+06,5.200000e+01,7.000000e+00,19.366188,-99.135491
75%,3.543941e+06,6.300000e+01,1.200000e+01,19.430791,-99.088303
max,4.145080e+06,1.000000e+09,1.700000e+01,72.449893,138.600404

In [15]:
df_complete.isnull().mean()

id_folio                   0.000000
fecha_solicitud            0.000000
hora_solicitud             0.000000
tipo_de_entrada            0.000000
tema_solicitud             0.000000
sexo                       0.109728
edad                       0.874167
colonia_solicitud          0.498695
alcaldia_solicitud         0.498695
codigo_postal_solicitud    0.041476
estatus                    0.000000
fecha_concluido            0.060947
latitud                    0.571393
longitud                   0.606803
dtype: float64

In [16]:
df_complete.info()

<class 'pandas.DataFrame'>
RangeIndex: 2303176 entries, 0 to 2303175
Data columns (total 14 columns):
 #   Column                   Dtype
---  ------                   -----
 0   id_folio                 int64
 1   fecha_solicitud          str
 2   hora_solicitud           str
 3   tipo_de_entrada          str
 4   tema_solicitud           str
 5   sexo                     str
 6   edad                     float64
 7   colonia_solicitud        str
 8   alcaldia_solicitud       float64
 9   codigo_postal_solicitud  str
 10  estatus                  str
 11  fecha_concluido          str
 12  latitud                  float64
 13  longitud                 float64
dtypes: float64(4), int64(1), str(9)
memory usage: 464.5 MB

In [17]:
df_complete.nunique(dropna=True)

id_folio                   2303176
fecha_solicitud               1208
hora_solicitud              572941
tipo_de_entrada                 10
tema_solicitud                  72
sexo                             4
edad                           105
colonia_solicitud             1925
alcaldia_solicitud              16
codigo_postal_solicitud       4146
estatus                          5
fecha_concluido               1207
latitud                     900812
longitud                    853156
dtype: int64

# 4. Data Cleaning

## 4.1 Drop Columns with +40% null

In [18]:
df_complete.isnull().mean()*100

id_folio                    0.000000
fecha_solicitud             0.000000
hora_solicitud              0.000000
tipo_de_entrada             0.000000
tema_solicitud              0.000000
sexo                       10.972805
edad                       87.416724
colonia_solicitud          49.869528
alcaldia_solicitud         49.869528
codigo_postal_solicitud     4.147621
estatus                     0.000000
fecha_concluido             6.094714
latitud                    57.139272
longitud                   60.680295
dtype: float64

In [19]:
null_columns = ['edad','colonia_solicitud','latitud','longitud']
df_complete.drop(columns=null_columns, inplace=True)
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido
0,1751404,2023-01-11,10:35:26.541,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Autoridad Responsable,NaN
1,1752021,2023-01-11,12:45:18.413,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18
2,1752656,2023-01-11,14:59:29.499,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18
3,1752838,2023-01-11,16:39:57.5,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18
4,1752915,2023-01-11,17:38:06.237,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7710.0,Cerrado,2023-01-18
...,...,...,...,...,...,...,...,...,...,...
2303171,3938194,2026-02-10,11:26:54,Usuarios SUAC Dependencia,PODA,Femenino,NaN,08730,Cerrado,2026-02-10
2303172,3938459,2026-02-10,12:11:44,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,NaN,09720,Cerrado,2026-03-12
2303173,3938818,2026-02-10,13:04:29,Portal Ciudadano SUAC,SOCAVÓN,Masculino,NaN,07080,Cerrado,2026-03-19
2303174,3938923,2026-02-10,13:19:40,Operador Telefónico - Ventanilla,SERVICIOS DE SALUD,Femenino,NaN,NaN,Cerrado,2026-02-18
2303175,3939023,2026-02-10,13:35:10,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,NaN,04300,Cerrado,2026-02-19

In [20]:
df_complete.isnull().mean()*100

id_folio                    0.000000
fecha_solicitud             0.000000
hora_solicitud              0.000000
tipo_de_entrada             0.000000
tema_solicitud              0.000000
sexo                       10.972805
alcaldia_solicitud         49.869528
codigo_postal_solicitud     4.147621
estatus                     0.000000
fecha_concluido             6.094714
dtype: float64

## 4.2 Date and Time Handling

### 4.2.1 Parse dates and times

In [21]:
df_complete['fecha_solicitud'] = pd.to_datetime(df_complete['fecha_solicitud'], format='%Y-%m-%d')
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido
0,1751404,2023-01-11,10:35:26.541,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Autoridad Responsable,NaN
1,1752021,2023-01-11,12:45:18.413,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18
2,1752656,2023-01-11,14:59:29.499,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18
3,1752838,2023-01-11,16:39:57.5,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18
4,1752915,2023-01-11,17:38:06.237,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7710.0,Cerrado,2023-01-18
...,...,...,...,...,...,...,...,...,...,...
2303171,3938194,2026-02-10,11:26:54,Usuarios SUAC Dependencia,PODA,Femenino,NaN,08730,Cerrado,2026-02-10
2303172,3938459,2026-02-10,12:11:44,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,NaN,09720,Cerrado,2026-03-12
2303173,3938818,2026-02-10,13:04:29,Portal Ciudadano SUAC,SOCAVÓN,Masculino,NaN,07080,Cerrado,2026-03-19
2303174,3938923,2026-02-10,13:19:40,Operador Telefónico - Ventanilla,SERVICIOS DE SALUD,Femenino,NaN,NaN,Cerrado,2026-02-18
2303175,3939023,2026-02-10,13:35:10,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,NaN,04300,Cerrado,2026-02-19

In [22]:
df_complete['fecha_concluido'] = pd.to_datetime(df_complete['fecha_concluido'], format='%Y-%m-%d')
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido
0,1751404,2023-01-11,10:35:26.541,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Autoridad Responsable,NaT
1,1752021,2023-01-11,12:45:18.413,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18
2,1752656,2023-01-11,14:59:29.499,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18
3,1752838,2023-01-11,16:39:57.5,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18
4,1752915,2023-01-11,17:38:06.237,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7710.0,Cerrado,2023-01-18
...,...,...,...,...,...,...,...,...,...,...
2303171,3938194,2026-02-10,11:26:54,Usuarios SUAC Dependencia,PODA,Femenino,NaN,08730,Cerrado,2026-02-10
2303172,3938459,2026-02-10,12:11:44,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,NaN,09720,Cerrado,2026-03-12
2303173,3938818,2026-02-10,13:04:29,Portal Ciudadano SUAC,SOCAVÓN,Masculino,NaN,07080,Cerrado,2026-03-19
2303174,3938923,2026-02-10,13:19:40,Operador Telefónico - Ventanilla,SERVICIOS DE SALUD,Femenino,NaN,NaN,Cerrado,2026-02-18
2303175,3939023,2026-02-10,13:35:10,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,NaN,04300,Cerrado,2026-02-19

In [23]:
df_complete['hora_solicitud_dt'] = pd.to_datetime(df_complete['hora_solicitud'], format='mixed', errors='coerce')
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,hora_solicitud_dt
0,1751404,2023-01-11,10:35:26.541,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Autoridad Responsable,NaT,2026-09-24 10:35:26.541
1,1752021,2023-01-11,12:45:18.413,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,2026-09-24 12:45:18.413
2,1752656,2023-01-11,14:59:29.499,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,2026-09-24 14:59:29.499
3,1752838,2023-01-11,16:39:57.5,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,2026-09-24 16:39:57.500
4,1752915,2023-01-11,17:38:06.237,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7710.0,Cerrado,2023-01-18,2026-09-24 17:38:06.237
...,...,...,...,...,...,...,...,...,...,...,...
2303171,3938194,2026-02-10,11:26:54,Usuarios SUAC Dependencia,PODA,Femenino,NaN,08730,Cerrado,2026-02-10,2026-09-24 11:26:54.000
2303172,3938459,2026-02-10,12:11:44,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,NaN,09720,Cerrado,2026-03-12,2026-09-24 12:11:44.000
2303173,3938818,2026-02-10,13:04:29,Portal Ciudadano SUAC,SOCAVÓN,Masculino,NaN,07080,Cerrado,2026-03-19,2026-09-24 13:04:29.000
2303174,3938923,2026-02-10,13:19:40,Operador Telefónico - Ventanilla,SERVICIOS DE SALUD,Femenino,NaN,NaN,Cerrado,2026-02-18,2026-09-24 13:19:40.000
2303175,3939023,2026-02-10,13:35:10,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,NaN,04300,Cerrado,2026-02-19,2026-09-24 13:35:10.000

In [24]:
df_complete['fecha_hora_solicitud'] = df_complete['fecha_solicitud'] + (df_complete['hora_solicitud_dt'] - df_complete['hora_solicitud_dt'].dt.normalize())
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,hora_solicitud_dt,fecha_hora_solicitud
0,1751404,2023-01-11,10:35:26.541,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Autoridad Responsable,NaT,2026-09-24 10:35:26.541,2023-01-11 10:35:26.541
1,1752021,2023-01-11,12:45:18.413,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,2026-09-24 12:45:18.413,2023-01-11 12:45:18.413
2,1752656,2023-01-11,14:59:29.499,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,2026-09-24 14:59:29.499,2023-01-11 14:59:29.499
3,1752838,2023-01-11,16:39:57.5,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,2026-09-24 16:39:57.500,2023-01-11 16:39:57.500
4,1752915,2023-01-11,17:38:06.237,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7710.0,Cerrado,2023-01-18,2026-09-24 17:38:06.237,2023-01-11 17:38:06.237
...,...,...,...,...,...,...,...,...,...,...,...,...
2303171,3938194,2026-02-10,11:26:54,Usuarios SUAC Dependencia,PODA,Femenino,NaN,08730,Cerrado,2026-02-10,2026-09-24 11:26:54.000,2026-02-10 11:26:54.000
2303172,3938459,2026-02-10,12:11:44,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,NaN,09720,Cerrado,2026-03-12,2026-09-24 12:11:44.000,2026-02-10 12:11:44.000
2303173,3938818,2026-02-10,13:04:29,Portal Ciudadano SUAC,SOCAVÓN,Masculino,NaN,07080,Cerrado,2026-03-19,2026-09-24 13:04:29.000,2026-02-10 13:04:29.000
2303174,3938923,2026-02-10,13:19:40,Operador Telefónico - Ventanilla,SERVICIOS DE SALUD,Femenino,NaN,NaN,Cerrado,2026-02-18,2026-09-24 13:19:40.000,2026-02-10 13:19:40.000
2303175,3939023,2026-02-10,13:35:10,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,NaN,04300,Cerrado,2026-02-19,2026-09-24 13:35:10.000,2026-02-10 13:35:10.000

In [25]:
df_complete['hora_solicitud'] = pd.to_datetime(df_complete['hora_solicitud'], format='mixed', errors='coerce').dt.hour
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,hora_solicitud_dt,fecha_hora_solicitud
0,1751404,2023-01-11,10,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Autoridad Responsable,NaT,2026-09-24 10:35:26.541,2023-01-11 10:35:26.541
1,1752021,2023-01-11,12,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,2026-09-24 12:45:18.413,2023-01-11 12:45:18.413
2,1752656,2023-01-11,14,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,2026-09-24 14:59:29.499,2023-01-11 14:59:29.499
3,1752838,2023-01-11,16,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,2026-09-24 16:39:57.500,2023-01-11 16:39:57.500
4,1752915,2023-01-11,17,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7710.0,Cerrado,2023-01-18,2026-09-24 17:38:06.237,2023-01-11 17:38:06.237
...,...,...,...,...,...,...,...,...,...,...,...,...
2303171,3938194,2026-02-10,11,Usuarios SUAC Dependencia,PODA,Femenino,NaN,08730,Cerrado,2026-02-10,2026-09-24 11:26:54.000,2026-02-10 11:26:54.000
2303172,3938459,2026-02-10,12,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,NaN,09720,Cerrado,2026-03-12,2026-09-24 12:11:44.000,2026-02-10 12:11:44.000
2303173,3938818,2026-02-10,13,Portal Ciudadano SUAC,SOCAVÓN,Masculino,NaN,07080,Cerrado,2026-03-19,2026-09-24 13:04:29.000,2026-02-10 13:04:29.000
2303174,3938923,2026-02-10,13,Operador Telefónico - Ventanilla,SERVICIOS DE SALUD,Femenino,NaN,NaN,Cerrado,2026-02-18,2026-09-24 13:19:40.000,2026-02-10 13:19:40.000
2303175,3939023,2026-02-10,13,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,NaN,04300,Cerrado,2026-02-19,2026-09-24 13:35:10.000,2026-02-10 13:35:10.000

### 4.2.2 Extract day and month

In [26]:
df_complete['dia_solicitud'] = df_complete['fecha_solicitud'].dt.day_name()
df_complete['mes_solicitud'] = df_complete['fecha_solicitud'].dt.month_name()
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,hora_solicitud_dt,fecha_hora_solicitud,dia_solicitud,mes_solicitud
0,1751404,2023-01-11,10,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Autoridad Responsable,NaT,2026-09-24 10:35:26.541,2023-01-11 10:35:26.541,Wednesday,January
1,1752021,2023-01-11,12,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,2026-09-24 12:45:18.413,2023-01-11 12:45:18.413,Wednesday,January
2,1752656,2023-01-11,14,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,2026-09-24 14:59:29.499,2023-01-11 14:59:29.499,Wednesday,January
3,1752838,2023-01-11,16,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,2026-09-24 16:39:57.500,2023-01-11 16:39:57.500,Wednesday,January
4,1752915,2023-01-11,17,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7710.0,Cerrado,2023-01-18,2026-09-24 17:38:06.237,2023-01-11 17:38:06.237,Wednesday,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2303171,3938194,2026-02-10,11,Usuarios SUAC Dependencia,PODA,Femenino,NaN,08730,Cerrado,2026-02-10,2026-09-24 11:26:54.000,2026-02-10 11:26:54.000,Tuesday,February
2303172,3938459,2026-02-10,12,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,NaN,09720,Cerrado,2026-03-12,2026-09-24 12:11:44.000,2026-02-10 12:11:44.000,Tuesday,February
2303173,3938818,2026-02-10,13,Portal Ciudadano SUAC,SOCAVÓN,Masculino,NaN,07080,Cerrado,2026-03-19,2026-09-24 13:04:29.000,2026-02-10 13:04:29.000,Tuesday,February
2303174,3938923,2026-02-10,13,Operador Telefónico - Ventanilla,SERVICIOS DE SALUD,Femenino,NaN,NaN,Cerrado,2026-02-18,2026-09-24 13:19:40.000,2026-02-10 13:19:40.000,Tuesday,February
2303175,3939023,2026-02-10,13,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,NaN,04300,Cerrado,2026-02-19,2026-09-24 13:35:10.000,2026-02-10 13:35:10.000,Tuesday,February

### 4.2.3 Encode hour

In [27]:
df_complete['hora_sin'] = np.sin(2 * np.pi * df_complete['hora_solicitud'] / 24)
df_complete['hora_cos'] = np.cos(2 * np.pi * df_complete['hora_solicitud'] / 24)

### 4.2.4 Obtain Target Variable

In [28]:
df_complete['tiempo_resolución'] = (df_complete['fecha_concluido'] - df_complete['fecha_solicitud']).dt.total_seconds() / 86400
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,hora_solicitud_dt,fecha_hora_solicitud,dia_solicitud,mes_solicitud,hora_sin,hora_cos,tiempo_resolución
0,1751404,2023-01-11,10,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Autoridad Responsable,NaT,2026-09-24 10:35:26.541,2023-01-11 10:35:26.541,Wednesday,January,5.000000e-01,-0.866025,NaN
1,1752021,2023-01-11,12,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,2026-09-24 12:45:18.413,2023-01-11 12:45:18.413,Wednesday,January,1.224647e-16,-1.000000,7.0
2,1752656,2023-01-11,14,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,2026-09-24 14:59:29.499,2023-01-11 14:59:29.499,Wednesday,January,-5.000000e-01,-0.866025,7.0
3,1752838,2023-01-11,16,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,2026-09-24 16:39:57.500,2023-01-11 16:39:57.500,Wednesday,January,-8.660254e-01,-0.500000,7.0
4,1752915,2023-01-11,17,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7710.0,Cerrado,2023-01-18,2026-09-24 17:38:06.237,2023-01-11 17:38:06.237,Wednesday,January,-9.659258e-01,-0.258819,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2303171,3938194,2026-02-10,11,Usuarios SUAC Dependencia,PODA,Femenino,NaN,08730,Cerrado,2026-02-10,2026-09-24 11:26:54.000,2026-02-10 11:26:54.000,Tuesday,February,2.588190e-01,-0.965926,0.0
2303172,3938459,2026-02-10,12,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,NaN,09720,Cerrado,2026-03-12,2026-09-24 12:11:44.000,2026-02-10 12:11:44.000,Tuesday,February,1.224647e-16,-1.000000,30.0
2303173,3938818,2026-02-10,13,Portal Ciudadano SUAC,SOCAVÓN,Masculino,NaN,07080,Cerrado,2026-03-19,2026-09-24 13:04:29.000,2026-02-10 13:04:29.000,Tuesday,February,-2.588190e-01,-0.965926,37.0
2303174,3938923,2026-02-10,13,Operador Telefónico - Ventanilla,SERVICIOS DE SALUD,Femenino,NaN,NaN,Cerrado,2026-02-18,2026-09-24 13:19:40.000,2026-02-10 13:19:40.000,Tuesday,February,-2.588190e-01,-0.965926,8.0
2303175,3939023,2026-02-10,13,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,NaN,04300,Cerrado,2026-02-19,2026-09-24 13:35:10.000,2026-02-10 13:35:10.000,Tuesday,February,-2.588190e-01,-0.965926,9.0

In [29]:
df_complete['tiempo_resolución_con_hora'] = (df_complete['fecha_concluido'] - df_complete['fecha_hora_solicitud']).dt.total_seconds() / 86400
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,hora_solicitud_dt,fecha_hora_solicitud,dia_solicitud,mes_solicitud,hora_sin,hora_cos,tiempo_resolución,tiempo_resolución_con_hora
0,1751404,2023-01-11,10,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Autoridad Responsable,NaT,2026-09-24 10:35:26.541,2023-01-11 10:35:26.541,Wednesday,January,5.000000e-01,-0.866025,NaN,NaN
1,1752021,2023-01-11,12,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,2026-09-24 12:45:18.413,2023-01-11 12:45:18.413,Wednesday,January,1.224647e-16,-1.000000,7.0,6.468537
2,1752656,2023-01-11,14,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,2026-09-24 14:59:29.499,2023-01-11 14:59:29.499,Wednesday,January,-5.000000e-01,-0.866025,7.0,6.375353
3,1752838,2023-01-11,16,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,2026-09-24 16:39:57.500,2023-01-11 16:39:57.500,Wednesday,January,-8.660254e-01,-0.500000,7.0,6.305584
4,1752915,2023-01-11,17,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7710.0,Cerrado,2023-01-18,2026-09-24 17:38:06.237,2023-01-11 17:38:06.237,Wednesday,January,-9.659258e-01,-0.258819,7.0,6.265206
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2303171,3938194,2026-02-10,11,Usuarios SUAC Dependencia,PODA,Femenino,NaN,08730,Cerrado,2026-02-10,2026-09-24 11:26:54.000,2026-02-10 11:26:54.000,Tuesday,February,2.588190e-01,-0.965926,0.0,-0.477014
2303172,3938459,2026-02-10,12,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,NaN,09720,Cerrado,2026-03-12,2026-09-24 12:11:44.000,2026-02-10 12:11:44.000,Tuesday,February,1.224647e-16,-1.000000,30.0,29.491852
2303173,3938818,2026-02-10,13,Portal Ciudadano SUAC,SOCAVÓN,Masculino,NaN,07080,Cerrado,2026-03-19,2026-09-24 13:04:29.000,2026-02-10 13:04:29.000,Tuesday,February,-2.588190e-01,-0.965926,37.0,36.455220
2303174,3938923,2026-02-10,13,Operador Telefónico - Ventanilla,SERVICIOS DE SALUD,Femenino,NaN,NaN,Cerrado,2026-02-18,2026-09-24 13:19:40.000,2026-02-10 13:19:40.000,Tuesday,February,-2.588190e-01,-0.965926,8.0,7.444676
2303175,3939023,2026-02-10,13,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,NaN,04300,Cerrado,2026-02-19,2026-09-24 13:35:10.000,2026-02-10 13:35:10.000,Tuesday,February,-2.588190e-01,-0.965926,9.0,8.433912

### 4.2.5 Erase atypical entries with 0 resolution time

In [30]:
zero_time_entries = df_complete[['tema_solicitud','tipo_de_entrada']][df_complete['tiempo_resolución_con_hora'] <= 0]
zero_time_entries.value_counts()

tema_solicitud                               tipo_de_entrada
OTRO                                         Interoperabilidad Iztapalapa        140490
FUGA DE AGUA                                 Interoperabilidad SACMEX              6000
FALTA DE AGUA                                Interoperabilidad SACMEX              3947
PODA                                         Usuarios SUAC Dependencia             3829
OTRO                                         Interoperabilidad Miguel Hidalgo      3206
                                                                                  ...
QUEJA SEGUIMIENTO TRÁMITE                    Usuarios SUAC Dependencia                1
TERRENO / VIVIENDA ABANDONADA                App CDMX                                 1
RETIRO ÁRBOL                                 Operador Telefónico LOCATEL              1
SOLICITUD Y MANTENIMIENTO DE ALERTA SÍSMICA  Whatsapp                                 1
QUEJA SEGUIMIENTO TRÁMITE                    App CDMX                                 1
Name: count, Length: 365, dtype: int64

In [31]:
df_complete = df_complete[df_complete['tiempo_resolución_con_hora'] > 0]

## 4.3 Zip Code Cleaning

### 4.3.1 Standardize Zip Code Format

In [32]:
patterns = df_complete['codigo_postal_solicitud'].dropna().apply(
    lambda x: ''.join(['d' if c.isdigit() else ('a' if c.isalpha() else c) for c in str(x).strip()])
)
patterns.value_counts()

codigo_postal_solicitud
ddddd      1576310
dddd        115508
-d          109979
dddd.d       80277
ddddd.d      25867
-d.d          1090
              1005
d               21
d.d             13
dd              13
ddd             10
aaaa             4
dd.dd            2
ddd.d            1
dddd*            1
dddda            1
dddd.            1
ddadd            1
daddd            1
dd dd            1
Name: count, dtype: int64

In [33]:
def clean_zc(x):
    if pd.isna(x):
        return None
    x = str(x).strip().rstrip('.')
    if x == '':
        return None
    try:
        result = str(int(float(x))).zfill(5)
        if len(result) > 5 or int(result) < 1000:
            return None
        return result
    except ValueError:
        return None

In [34]:
df_complete['codigo_postal_solicitud'] = df_complete['codigo_postal_solicitud'].apply(clean_zc)

In [35]:
patterns = df_complete['codigo_postal_solicitud'].dropna().apply(
    lambda x: ''.join(['d' if c.isdigit() else ('a' if c.isalpha() else c) for c in str(x).strip()])
)
patterns.value_counts()

codigo_postal_solicitud
ddddd    1797668
Name: count, dtype: int64

## 4.4 Impute Municipality

### 4.4.1 Map Municipality Number to Name

In [36]:
df_complete['alcaldia_solicitud'].value_counts()

alcaldia_solicitud
7.0     272852
5.0      92295
15.0     89689
3.0      77424
12.0     68665
10.0     57799
14.0     51061
2.0      47490
6.0      40628
13.0     40434
16.0     31521
17.0     20765
11.0     17572
8.0      14225
4.0      13443
9.0      10772
Name: count, dtype: int64

In [37]:
municipalities = {2.0:'Azcapotzalco',3.0:'Coyoacán',4.0:'Cuajimalpa de Morelos',5.0:'Gustavo A. Madero',6.0:'Iztacalco',7.0:'Iztapalapa',8.0:'La Magdalena Contreras',
9.0:'Milpa Alta',10.0:'Álvaro Obregón',11.0:'Tláhuac',12.0:'Tlalpan',13.0:'Xochimilco',14.0:'Benito Juárez',15.0:'Cuauhtémoc',16.0:'Miguel Hidalgo',
17.0:'Venustiano Carranza'}

In [38]:
df_complete['alcaldia_solicitud'] = df_complete['alcaldia_solicitud'].map(municipalities)
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,hora_solicitud_dt,fecha_hora_solicitud,dia_solicitud,mes_solicitud,hora_sin,hora_cos,tiempo_resolución,tiempo_resolución_con_hora
1,1752021,2023-01-11,12,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,Gustavo A. Madero,07700,Cerrado,2023-01-18,2026-09-24 12:45:18.413,2023-01-11 12:45:18.413,Wednesday,January,1.224647e-16,-1.000000,7.0,6.468537
2,1752656,2023-01-11,14,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,Gustavo A. Madero,07700,Cerrado,2023-01-18,2026-09-24 14:59:29.499,2023-01-11 14:59:29.499,Wednesday,January,-5.000000e-01,-0.866025,7.0,6.375353
3,1752838,2023-01-11,16,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,Gustavo A. Madero,07700,Cerrado,2023-01-18,2026-09-24 16:39:57.500,2023-01-11 16:39:57.500,Wednesday,January,-8.660254e-01,-0.500000,7.0,6.305584
4,1752915,2023-01-11,17,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,Gustavo A. Madero,07710,Cerrado,2023-01-18,2026-09-24 17:38:06.237,2023-01-11 17:38:06.237,Wednesday,January,-9.659258e-01,-0.258819,7.0,6.265206
5,1753053,2023-01-11,19,Portal Ciudadano SUAC,SOLICITUD DE VIGILANCIA POLICIACA,NaN,Gustavo A. Madero,07000,Cerrado,2023-01-18,2026-09-24 19:27:47.457,2023-01-11 19:27:47.457,Wednesday,January,-9.659258e-01,0.258819,7.0,6.189034
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2303170,3937959,2026-02-10,10,Operador Telefónico LOCATEL,SOPORTE A TRÁMITES Y APLICACIONES DIGITALES,No especificado,NaN,NaN,Cerrado,2026-03-02,2026-09-24 10:48:30.000,2026-02-10 10:48:30.000,Tuesday,February,5.000000e-01,-0.866025,20.0,19.549653
2303172,3938459,2026-02-10,12,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,NaN,09720,Cerrado,2026-03-12,2026-09-24 12:11:44.000,2026-02-10 12:11:44.000,Tuesday,February,1.224647e-16,-1.000000,30.0,29.491852
2303173,3938818,2026-02-10,13,Portal Ciudadano SUAC,SOCAVÓN,Masculino,NaN,07080,Cerrado,2026-03-19,2026-09-24 13:04:29.000,2026-02-10 13:04:29.000,Tuesday,February,-2.588190e-01,-0.965926,37.0,36.455220
2303174,3938923,2026-02-10,13,Operador Telefónico - Ventanilla,SERVICIOS DE SALUD,Femenino,NaN,NaN,Cerrado,2026-02-18,2026-09-24 13:19:40.000,2026-02-10 13:19:40.000,Tuesday,February,-2.588190e-01,-0.965926,8.0,7.444676
2303175,3939023,2026-02-10,13,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,NaN,04300,Cerrado,2026-02-19,2026-09-24 13:35:10.000,2026-02-10 13:35:10.000,Tuesday,February,-2.588190e-01,-0.965926,9.0,8.433912

In [39]:
df_complete['alcaldia_solicitud'].value_counts()

alcaldia_solicitud
Iztapalapa                272852
Gustavo A. Madero          92295
Cuauhtémoc                 89689
Coyoacán                   77424
Tlalpan                    68665
Álvaro Obregón             57799
Benito Juárez              51061
Azcapotzalco               47490
Iztacalco                  40628
Xochimilco                 40434
Miguel Hidalgo             31521
Venustiano Carranza        20765
Tláhuac                    17572
La Magdalena Contreras     14225
Cuajimalpa de Morelos      13443
Milpa Alta                 10772
Name: count, dtype: int64

### 4.4.2 Impute Municipality with Zip Code

In [40]:
municipality_zc = {
    '01':'Álvaro Obregón',
    '02':'Azcapotzalco',
    '03':'Benito Juárez',
    '04':'Coyoacán',
    '05':'Cuajimalpa de Morelos',
    '06':'Cuauhtémoc',
    '07':'Gustavo A. Madero',
    '08':'Iztacalco',
    '09':'Iztapalapa',
    '10':'La Magdalena Contreras',
    '11':'Miguel Hidalgo',
    '12':'Milpa Alta',
    '13':'Tláhuac',
    '14':'Tlalpan',
    '15':'Venustiano Carranza',
    '16':'Xochimilco'
}

In [41]:
missing_mask = df_complete['alcaldia_solicitud'].isna()

df_complete.loc[missing_mask, 'alcaldia_solicitud'] = (
    df_complete.loc[missing_mask, 'codigo_postal_solicitud']
    .astype(str)
    .str[:2]
    .map(municipality_zc)
)

In [42]:
df_complete.isnull().mean()

id_folio                      0.000000
fecha_solicitud               0.000000
hora_solicitud                0.000000
tipo_de_entrada               0.000000
tema_solicitud                0.000000
sexo                          0.123840
alcaldia_solicitud            0.037990
codigo_postal_solicitud       0.094077
estatus                       0.000000
fecha_concluido               0.000000
hora_solicitud_dt             0.000000
fecha_hora_solicitud          0.000000
dia_solicitud                 0.000000
mes_solicitud                 0.000000
hora_sin                      0.000000
hora_cos                      0.000000
tiempo_resolución             0.000000
tiempo_resolución_con_hora    0.000000
dtype: float64

## 4.5 Impute Gender

In [43]:
df_complete[['sexo']] = df_complete[['sexo']].fillna('No especificado')

In [44]:
df_complete['sexo'] = df_complete['sexo'].replace(to_replace='3', value='No especificado')

In [45]:
df_complete['sexo'].value_counts()

sexo
No especificado    1019254
Femenino            538251
Masculino           426844
Name: count, dtype: int64

## 4.6 Drop NAs

In [46]:
df_complete.dropna(subset=['alcaldia_solicitud','codigo_postal_solicitud','tiempo_resolución','tiempo_resolución_con_hora'],inplace=True)
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,hora_solicitud_dt,fecha_hora_solicitud,dia_solicitud,mes_solicitud,hora_sin,hora_cos,tiempo_resolución,tiempo_resolución_con_hora
1,1752021,2023-01-11,12,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07700,Cerrado,2023-01-18,2026-09-24 12:45:18.413,2023-01-11 12:45:18.413,Wednesday,January,1.224647e-16,-1.000000e+00,7.0,6.468537
2,1752656,2023-01-11,14,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07700,Cerrado,2023-01-18,2026-09-24 14:59:29.499,2023-01-11 14:59:29.499,Wednesday,January,-5.000000e-01,-8.660254e-01,7.0,6.375353
3,1752838,2023-01-11,16,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07700,Cerrado,2023-01-18,2026-09-24 16:39:57.500,2023-01-11 16:39:57.500,Wednesday,January,-8.660254e-01,-5.000000e-01,7.0,6.305584
4,1752915,2023-01-11,17,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07710,Cerrado,2023-01-18,2026-09-24 17:38:06.237,2023-01-11 17:38:06.237,Wednesday,January,-9.659258e-01,-2.588190e-01,7.0,6.265206
5,1753053,2023-01-11,19,Portal Ciudadano SUAC,SOLICITUD DE VIGILANCIA POLICIACA,No especificado,Gustavo A. Madero,07000,Cerrado,2023-01-18,2026-09-24 19:27:47.457,2023-01-11 19:27:47.457,Wednesday,January,-9.659258e-01,2.588190e-01,7.0,6.189034
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2303167,3936163,2026-02-09,16,Usuarios SUAC Dependencia,PAVIMENTACIÓN / REENCARPETADO,Femenino,Azcapotzalco,02200,Cerrado,2026-03-09,2026-09-24 16:30:46.000,2026-02-09 16:30:46.000,Monday,February,-8.660254e-01,-5.000000e-01,28.0,27.311968
2303168,3936548,2026-02-09,18,Usuarios SUAC Dependencia,FALTA DE AGUA,No especificado,Coyoacán,04600,Cerrado,2026-02-16,2026-09-24 18:10:20.000,2026-02-09 18:10:20.000,Monday,February,-1.000000e+00,-1.836970e-16,7.0,6.242824
2303172,3938459,2026-02-10,12,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,Iztapalapa,09720,Cerrado,2026-03-12,2026-09-24 12:11:44.000,2026-02-10 12:11:44.000,Tuesday,February,1.224647e-16,-1.000000e+00,30.0,29.491852
2303173,3938818,2026-02-10,13,Portal Ciudadano SUAC,SOCAVÓN,Masculino,Gustavo A. Madero,07080,Cerrado,2026-03-19,2026-09-24 13:04:29.000,2026-02-10 13:04:29.000,Tuesday,February,-2.588190e-01,-9.659258e-01,37.0,36.455220
2303175,3939023,2026-02-10,13,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,Coyoacán,04300,Cerrado,2026-02-19,2026-09-24 13:35:10.000,2026-02-10 13:35:10.000,Tuesday,February,-2.588190e-01,-9.659258e-01,9.0,8.433912

## 4.7 Exclude Cancelled Requests

In [47]:
df_complete['estatus'].value_counts()

estatus
Cerrado                  1314032
Atendido                  478036
Autoridad Responsable       4317
Cancelado                    621
Recibido                     276
Name: count, dtype: int64

In [49]:
df_complete.shape

(1797282, 18)

In [50]:
df_complete = df_complete[df_complete['estatus'] != 'Cancelado']

In [51]:
df_complete.shape

(1796661, 18)

## 4.8 Drop Remaining Columns

In [52]:
columns_drop = ['id_folio','fecha_solicitud','hora_solicitud','fecha_hora_solicitud','hora_solicitud_dt','estatus','fecha_concluido']
df_complete.drop(columns=columns_drop,inplace=True)
df_complete

,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,codigo_postal_solicitud,dia_solicitud,mes_solicitud,hora_sin,hora_cos,tiempo_resolución,tiempo_resolución_con_hora
1,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07700,Wednesday,January,1.224647e-16,-1.000000e+00,7.0,6.468537
2,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07700,Wednesday,January,-5.000000e-01,-8.660254e-01,7.0,6.375353
3,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07700,Wednesday,January,-8.660254e-01,-5.000000e-01,7.0,6.305584
4,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07710,Wednesday,January,-9.659258e-01,-2.588190e-01,7.0,6.265206
5,Portal Ciudadano SUAC,SOLICITUD DE VIGILANCIA POLICIACA,No especificado,Gustavo A. Madero,07000,Wednesday,January,-9.659258e-01,2.588190e-01,7.0,6.189034
...,...,...,...,...,...,...,...,...,...,...,...
2303167,Usuarios SUAC Dependencia,PAVIMENTACIÓN / REENCARPETADO,Femenino,Azcapotzalco,02200,Monday,February,-8.660254e-01,-5.000000e-01,28.0,27.311968
2303168,Usuarios SUAC Dependencia,FALTA DE AGUA,No especificado,Coyoacán,04600,Monday,February,-1.000000e+00,-1.836970e-16,7.0,6.242824
2303172,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,Iztapalapa,09720,Tuesday,February,1.224647e-16,-1.000000e+00,30.0,29.491852
2303173,Portal Ciudadano SUAC,SOCAVÓN,Masculino,Gustavo A. Madero,07080,Tuesday,February,-2.588190e-01,-9.659258e-01,37.0,36.455220
2303175,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,Coyoacán,04300,Tuesday,February,-2.588190e-01,-9.659258e-01,9.0,8.433912

# 5. Visualizations

In [53]:
columns_df = df_complete.drop(columns=['tema_solicitud','codigo_postal_solicitud','hora_sin','hora_cos','tiempo_resolución','tiempo_resolución_con_hora']).columns.to_list()
columns_df

['tipo_de_entrada',
 'sexo',
 'alcaldia_solicitud',
 'dia_solicitud',
 'mes_solicitud']

## 5.1 Histograms

In [ ]:
top_n = 20
topic_count = df_complete['tema_solicitud'].value_counts()

count_without_otro = topic_count.drop(labels='OTRO')

top_topics = count_without_otro.head(top_n)
remainder = count_without_otro.iloc[top_n:].sum() + topic_count['OTRO']

series_plot = pd.concat([top_topics, pd.Series({'OTRO': remainder})])

fig = px.bar(x=series_plot.index, y=series_plot.values)
fig.update_layout(title='Top 20 topics (others grouped in "Otro")',xaxis_title='tema_solicitud', yaxis_title='Count')
fig.show()

In [ ]:
for param in columns_df:
    param_values = df_complete[param].value_counts()
    fig = px.histogram(x=param_values.index,y=param_values.values,nbins=len(param_values.index))
    fig.update_layout(title='Count of entries per topic',xaxis_title=f'{param}', yaxis_title='Count')
    fig.show()

## 5.2 Boxplots

In [ ]:
top_n = 20
topic_count = df_complete['tema_solicitud'].value_counts()
count_without_otro = topic_count.drop(labels='OTRO')
top_topics = count_without_otro.head(top_n).index

df_complete['tema_solicitud_grouped'] = df_complete['tema_solicitud'].where(
    df_complete['tema_solicitud'].isin(top_topics), other='OTRO'
)

y_col = 'tiempo_resolución_con_hora'

fig = px.box(df_complete, x='tema_solicitud_grouped', y=y_col, points=False)
fig.update_yaxes(type='log', title='Resolution time (log)')
fig.update_layout(title='Resolution time by topic (Top 20 + Otro)')
fig.show()

In [ ]:
y_col = 'tiempo_resolución_con_hora'

for param in columns_df:
    fig = px.box(df_complete,x=param,y=y_col, points=False)
    fig.update_yaxes(type='log',title='Resolution time (log)')
    fig.update_layout(title=f'Resolution time by {param}')
    fig.show()

# 6. Correlations

## 6.1 Numeric

In [58]:
df_complete['codigo_postal_solicitud'] = df_complete['codigo_postal_solicitud'].astype("float")

In [59]:
df_complete.corr(numeric_only=True)

,codigo_postal_solicitud,hora_sin,hora_cos,tiempo_resolución,tiempo_resolución_con_hora
codigo_postal_solicitud,1.000000,0.041621,-0.035104,0.004345,0.004432
hora_sin,0.041621,1.000000,-0.383833,-0.011944,-0.009949
hora_cos,-0.035104,-0.383833,1.000000,-0.004568,-0.005828
tiempo_resolución,0.004345,-0.011944,-0.004568,1.000000,0.999997
tiempo_resolución_con_hora,0.004432,-0.009949,-0.005828,0.999997,1.000000

In [60]:
df_complete.drop(columns=['codigo_postal_solicitud'],inplace=True)
df_complete

,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,dia_solicitud,mes_solicitud,hora_sin,hora_cos,tiempo_resolución,tiempo_resolución_con_hora,tema_solicitud_grouped
1,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,Wednesday,January,1.224647e-16,-1.000000e+00,7.0,6.468537,FALTA DE AGUA
2,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,Wednesday,January,-5.000000e-01,-8.660254e-01,7.0,6.375353,FALTA DE AGUA
3,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,Wednesday,January,-8.660254e-01,-5.000000e-01,7.0,6.305584,FALTA DE AGUA
4,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,Wednesday,January,-9.659258e-01,-2.588190e-01,7.0,6.265206,FALTA DE AGUA
5,Portal Ciudadano SUAC,SOLICITUD DE VIGILANCIA POLICIACA,No especificado,Gustavo A. Madero,Wednesday,January,-9.659258e-01,2.588190e-01,7.0,6.189034,SOLICITUD DE VIGILANCIA POLICIACA
...,...,...,...,...,...,...,...,...,...,...,...
2303167,Usuarios SUAC Dependencia,PAVIMENTACIÓN / REENCARPETADO,Femenino,Azcapotzalco,Monday,February,-8.660254e-01,-5.000000e-01,28.0,27.311968,PAVIMENTACIÓN / REENCARPETADO
2303168,Usuarios SUAC Dependencia,FALTA DE AGUA,No especificado,Coyoacán,Monday,February,-1.000000e+00,-1.836970e-16,7.0,6.242824,FALTA DE AGUA
2303172,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,Iztapalapa,Tuesday,February,1.224647e-16,-1.000000e+00,30.0,29.491852,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO
2303173,Portal Ciudadano SUAC,SOCAVÓN,Masculino,Gustavo A. Madero,Tuesday,February,-2.588190e-01,-9.659258e-01,37.0,36.455220,OTRO
2303175,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,Coyoacán,Tuesday,February,-2.588190e-01,-9.659258e-01,9.0,8.433912,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO

## 6.2 Categorical

In [61]:
categories_list = columns_df + ['tema_solicitud_grouped']
categories_list

['tipo_de_entrada',
 'sexo',
 'alcaldia_solicitud',
 'dia_solicitud',
 'mes_solicitud',
 'tema_solicitud_grouped']

In [63]:
results_dict = {
    'Category' : [],
    'F-test' : [],
    'P-value' : [],
    'Eta^2' : []
}
for category in categories_list:
    variables_list = df_complete[category].value_counts().index.to_list()
    dict_arrays = {}
    for variable in variables_list:
        variable_array = df_complete['tiempo_resolución_con_hora'][df_complete[category] == variable].to_numpy()
        dict_arrays[variable] = variable_array
    F = f_oneway(*dict_arrays.values())
    mean_time = df_complete['tiempo_resolución_con_hora'].mean()
    group_mean = df_complete.groupby(category)['tiempo_resolución_con_hora'].mean()
    group_count = df_complete.groupby(category)['tiempo_resolución_con_hora'].count()
    ss_total = ((df_complete['tiempo_resolución_con_hora'] - mean_time)**2).sum()
    ss_effect = (((group_mean - mean_time)**2)*group_count).sum()
    eta_squared = ss_effect / ss_total
    results_dict['Category'].append(category)
    results_dict['F-test'].append(F.statistic.round(3))
    results_dict['P-value'].append(F.pvalue.round(11))
    results_dict['Eta^2'].append(eta_squared)

In [64]:
df_results = pd.DataFrame(results_dict)
df_results

                 Category    F-test  P-value     Eta^2
0         tipo_de_entrada  2329.403      0.0  0.011534
1                    sexo   222.042      0.0  0.000247
2      alcaldia_solicitud  1770.284      0.0  0.014565
3           dia_solicitud   190.236      0.0  0.000635
4           mes_solicitud   530.052      0.0  0.003235
5  tema_solicitud_grouped  4429.567      0.0  0.046992

In [65]:
df_complete.drop(columns='tema_solicitud_grouped', inplace=True)

# 7. Distributions

In [ ]:
fig = px.histogram(df_complete, x='tiempo_resolución_con_hora', nbins=200)
fig.update_layout(title='Resolution time distribution (days)', xaxis_title='Days', yaxis_title='Count')
fig.update_traces(xbins=dict(start=0))
fig.show()

df_complete['tiempo_resolución'].describe()

In [ ]:
time_log = np.log1p(df_complete['tiempo_resolución_con_hora'].to_numpy())
df_time_log = pd.DataFrame({
    'tiempo_resolución_con_hora' : time_log
})
fig = px.histogram(df_time_log, x='tiempo_resolución_con_hora', nbins=200)
fig.update_layout(title='Resolution time distribution (log days)', xaxis_title='Log days', yaxis_title='Count')
fig.update_traces(xbins=dict(start=0))
fig.show()
df_time_log['tiempo_resolución_con_hora'].describe()

# 8. Export

In [70]:
df_complete.to_csv(path_or_buf='../data/preprocessed/dataset_preprocessed.csv', index=False)

In [71]:
df_check = pd.read_csv('../data/preprocessed/dataset_preprocessed.csv')
df_check.head()

,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,dia_solicitud,mes_solicitud,hora_sin,hora_cos,tiempo_resolución,tiempo_resolución_con_hora
0,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,Wednesday,January,1.224647e-16,-1.000000,7.0,6.468537
1,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,Wednesday,January,-5.000000e-01,-0.866025,7.0,6.375353
2,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,Wednesday,January,-8.660254e-01,-0.500000,7.0,6.305584
3,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,Wednesday,January,-9.659258e-01,-0.258819,7.0,6.265206
4,Portal Ciudadano SUAC,SOLICITUD DE VIGILANCIA POLICIACA,No especificado,Gustavo A. Madero,Wednesday,January,-9.659258e-01,0.258819,7.0,6.189034