# Pre-procesamiento Datos Crudos

In [80]:
import pandas as pd
import plotly.express as px
import numpy as np
from sklearn.preprocessing import OneHotEncoder, TargetEncoder
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split

## Datos Crudos

In [81]:
data_2023 = "../data/raw/SUAC_2023.csv"
data_2024 = "../data/raw/SUAC_2024.csv"
data_2025 = "../data/raw/SUAC_2025.csv"
data_2026 = "../data/raw/SUAC_2026.csv"

In [82]:
df_2023 = pd.read_csv(data_2023)
df_2024 = pd.read_csv(data_2024)
df_2025 = pd.read_csv(data_2025)
df_2026 = pd.read_csv(data_2026)

/var/folders/t1/6m61dml920j5z0dm3z5bskw80000gn/T/ipykernel_74397/3567484953.py:1: DtypeWarning:

Columns (0: codigo_postal_solicitud) have mixed types. Specify dtype option on import or set low_memory=False.

/var/folders/t1/6m61dml920j5z0dm3z5bskw80000gn/T/ipykernel_74397/3567484953.py:2: DtypeWarning:

Columns (0: codigo_postal_solicitud) have mixed types. Specify dtype option on import or set low_memory=False.

In [83]:
df_2023.head()

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,edad,colonia_solicitud,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,latitud,longitud
0,1751404,2023-01-11,10:35:26.541,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Autoridad Responsable,NaN,NaN,NaN
1,1752021,2023-01-11,12:45:18.413,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
2,1752656,2023-01-11,14:59:29.499,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
3,1752838,2023-01-11,16:39:57.5,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
4,1752915,2023-01-11,17:38:06.237,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7710.0,Cerrado,2023-01-18,NaN,NaN

In [84]:
df_2024.head()

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,edad,colonia_solicitud,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,latitud,longitud
0,2547339,2024-04-19,21:16:24,App CDMX,DESAZOLVE,No especificado,NaN,SAN PEDRO EL CHICO,5.0,07480,Cerrado,2024-06-06,19.471184,-99.100071
1,2547340,2024-04-19,21:20:08,Operador Telefónico LOCATEL,RETIRO AMBULANTE,No especificado,NaN,NaN,NaN,04360,Cerrado,2024-05-20,NaN,NaN
2,2547341,2024-04-19,21:20:45,App CDMX,PODA,No especificado,NaN,NaN,NaN,NaN,Cerrado,2024-04-22,NaN,NaN
3,2547342,2024-04-19,21:21:06,App CDMX,SOLICITUD DE VIGILANCIA POLICIACA,No especificado,NaN,NaN,NaN,09500,Cerrado,2024-05-02,NaN,NaN
4,2547344,2024-04-19,21:27:55,App CDMX,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,NaN,EUZKADI,2.0,02660,Cerrado,2024-05-05,19.480044,-99.157328

In [85]:
df_2025.head()

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,edad,colonia_solicitud,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,latitud,longitud
0,3007414,2025-01-07,14:25:47,App CDMX,MANTENIMIENTO VÍA PÚBLICA,No especificado,NaN,NaN,NaN,NaN,Cerrado,2025-01-29,NaN,NaN
1,3000375,2025-01-01,00:16:01,App CDMX,SOLICITUD DE VIGILANCIA POLICIACA,No especificado,NaN,NaN,NaN,01160,Cerrado,2025-01-03,NaN,NaN
2,3008130,2025-01-08,08:00:55,App CDMX,OTRO,No especificado,NaN,NaN,NaN,NaN,Cerrado,2025-02-27,NaN,NaN
3,3000497,2025-01-01,16:13:58,App CDMX,MANTENIMIENTO PARQUE / ÁREA VERDE,No especificado,NaN,TLALPAN CENTRO,12.0,14000,Cerrado,2025-01-07,19.291450,-99.168547
4,3000498,2025-01-01,16:21:54,App CDMX,VERIFICACIÓN ADMINISTRATIVA,No especificado,NaN,CONSTITUCION DE 1917,7.0,09260,Cerrado,2025-01-06,19.352837,-99.058975

In [86]:
df_2026.head()

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,edad,colonia_solicitud,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,latitud,longitud
0,3841679,2026-01-01,07:15:46,App CDMX,FUGA DE AGUA,No especificado,NaN,NaN,NaN,09858,Atendido,2026-01-20,NaN,NaN
1,3841683,2026-01-01,07:39:01,Interoperabilidad SACMEX,FUGA DE AGUA,No especificado,NaN,SAN JUAN CERRO,7.0,9858,Atendido,2026-01-20,19.345325,-99.081876
2,3841684,2026-01-01,07:42:01.448,Portal Ciudadano SUAC,OTRO,Femenino,NaN,LAS CRUCES,8.0,10330,Atendido,2026-01-20,19.320363,-99.258278
3,3841686,2026-01-01,07:46:17,App CDMX,QUEJA DE TRANSPORTE PÚBLICO,No especificado,NaN,NaN,NaN,14376,Atendido,2026-01-06,NaN,NaN
4,3841687,2026-01-01,07:46:37,App CDMX,SOLICITUD DE VIGILANCIA POLICIACA,No especificado,NaN,NaN,NaN,09705,Atendido,2026-01-05,NaN,NaN

## Exploración Inicial

In [87]:
dfs = {
    2023: df_2023,
    2024: df_2024,
    2025: df_2025,
    2026: df_2026,
}

def explorar(df, nombre=""):
    print("=" * 70)
    print(f"  EXPLORACIÓN INICIAL — {nombre}")
    print("=" * 70)

    print(f"\nDimensiones: {df.shape[0]} filas × {df.shape[1]} columnas\n")

    print("--- info() ---")
    df.info()

In [88]:
for año, df in dfs.items():
    explorar(df, nombre=f"Año {año}")

======================================================================
  EXPLORACIÓN INICIAL — Año 2023
======================================================================

Dimensiones: 565558 filas × 14 columnas

--- info() ---
<class 'pandas.DataFrame'>
RangeIndex: 565558 entries, 0 to 565557
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id_folio                 565558 non-null  int64
 1   fecha_solicitud          565558 non-null  str
 2   hora_solicitud           565558 non-null  str
 3   tipo_de_entrada          565558 non-null  str
 4   tema_solicitud           565558 non-null  str
 5   sexo                     347177 non-null  str
 6   edad                     51857 non-null   float64
 7   colonia_solicitud        265184 non-null  str
 8   alcaldia_solicitud       265184 non-null  float64
 9   codigo_postal_solicitud  516043 non-null  object
 10  estatus                  565558 non-null  str
 11  fecha_concluido          561114 non-null  str
 12  latitud                  228154 non-null  float64
 13  longitud                 206204 non-null  float64
dtypes: float64(4), int64(1), object(1), str(8)
memory usage: 109.8+ MB
======================================================================
  EXPLORACIÓN INICIAL — Año 2024
======================================================================

Dimensiones: 631916 filas × 14 columnas

--- info() ---
<class 'pandas.DataFrame'>
RangeIndex: 631916 entries, 0 to 631915
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id_folio                 631916 non-null  int64
 1   fecha_solicitud          631916 non-null  str
 2   hora_solicitud           631916 non-null  str
 3   tipo_de_entrada          631916 non-null  str
 4   tema_solicitud           631916 non-null  str
 5   sexo                     617903 non-null  str
 6   edad                     85418 non-null   float64
 7   colonia_solicitud        328366 non-null  str
 8   alcaldia_solicitud       328366 non-null  float64
 9   codigo_postal_solicitud  600184 non-null  object
 10  estatus                  631916 non-null  str
 11  fecha_concluido          627189 non-null  str
 12  latitud                  234318 non-null  float64
 13  longitud                 207857 non-null  float64
dtypes: float64(4), int64(1), object(1), str(8)
memory usage: 123.9+ MB
======================================================================
  EXPLORACIÓN INICIAL — Año 2025
======================================================================

Dimensiones: 816437 filas × 14 columnas

--- info() ---
<class 'pandas.DataFrame'>
RangeIndex: 816437 entries, 0 to 816436
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id_folio                 816437 non-null  int64
 1   fecha_solicitud          816437 non-null  str
 2   hora_solicitud           816437 non-null  str
 3   tipo_de_entrada          816437 non-null  str
 4   tema_solicitud           816437 non-null  str
 5   sexo                     801183 non-null  str
 6   edad                     126538 non-null  float64
 7   colonia_solicitud        411388 non-null  str
 8   alcaldia_solicitud       411388 non-null  float64
 9   codigo_postal_solicitud  804927 non-null  str
 10  estatus                  816437 non-null  str
 11  fecha_concluido          784311 non-null  str
 12  latitud                  382247 non-null  float64
 13  longitud                 357671 non-null  float64
dtypes: float64(4), int64(1), str(9)
memory usage: 166.1 MB
======================================================================
  EXPLORACIÓN INICIAL — Año 2026
======================================================================

Dimensiones: 289265 filas × 14 columnas

--- info() ---
<class 'pandas.DataFrame'>
RangeIndex: 289265 entries, 0 to 289264
Data columns (total 14 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id_folio                 289265 non-null  int64
 1   fecha_solicitud          289265 non-null  str
 2   hora_solicitud           289265 non-null  str
 3   tipo_de_entrada          289265 non-null  str
 4   tema_solicitud           289265 non-null  str
 5   sexo                     284190 non-null  str
 6   edad                     26002 non-null   float64
 7   colonia_solicitud        149655 non-null  str
 8   alcaldia_solicitud       149655 non-null  float64
 9   codigo_postal_solicitud  286495 non-null  str
 10  estatus                  289265 non-null  str
 11  fecha_concluido          190190 non-null  str
 12  latitud                  142439 non-null  float64
 13  longitud                 133870 non-null  float64
dtypes: float64(4), int64(1), str(9)
memory usage: 59.2 MB

In [89]:
lista_df = [df_2023,df_2024,df_2025,df_2026]
for df in lista_df:
    df['codigo_postal_solicitud'] = df['codigo_postal_solicitud'].astype(str)

In [90]:
df_complete = pd.concat(lista_df, ignore_index=True)

In [91]:
df_complete.head()

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,edad,colonia_solicitud,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,latitud,longitud
0,1751404,2023-01-11,10:35:26.541,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Autoridad Responsable,NaN,NaN,NaN
1,1752021,2023-01-11,12:45:18.413,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
2,1752656,2023-01-11,14:59:29.499,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
3,1752838,2023-01-11,16:39:57.5,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
4,1752915,2023-01-11,17:38:06.237,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7710.0,Cerrado,2023-01-18,NaN,NaN

In [92]:
df_complete.shape

(2303176, 14)

In [93]:
df_complete.describe()

,id_folio,edad,alcaldia_solicitud,latitud,longitud
count,2.303176e+06,2.898150e+05,1.154593e+06,987158.000000,905602.000000
mean,2.946632e+06,3.501398e+03,8.550033e+00,18.582701,-99.123430
std,6.923618e+05,1.857546e+06,4.064176e+00,3.862915,0.922771
min,1.739063e+06,0.000000e+00,2.000000e+00,-43.708360,-165.893111
25%,2.348458e+06,4.000000e+01,6.000000e+00,19.315477,-99.174385
50%,2.951948e+06,5.200000e+01,7.000000e+00,19.366188,-99.135491
75%,3.543941e+06,6.300000e+01,1.200000e+01,19.430791,-99.088303
max,4.145080e+06,1.000000e+09,1.700000e+01,72.449893,138.600404

In [94]:
df_complete.isnull().mean()

id_folio                   0.000000
fecha_solicitud            0.000000
hora_solicitud             0.000000
tipo_de_entrada            0.000000
tema_solicitud             0.000000
sexo                       0.109728
edad                       0.874167
colonia_solicitud          0.498695
alcaldia_solicitud         0.498695
codigo_postal_solicitud    0.041476
estatus                    0.000000
fecha_concluido            0.060947
latitud                    0.571393
longitud                   0.606803
dtype: float64

In [95]:
df_complete.info()

<class 'pandas.DataFrame'>
RangeIndex: 2303176 entries, 0 to 2303175
Data columns (total 14 columns):
 #   Column                   Dtype
---  ------                   -----
 0   id_folio                 int64
 1   fecha_solicitud          str
 2   hora_solicitud           str
 3   tipo_de_entrada          str
 4   tema_solicitud           str
 5   sexo                     str
 6   edad                     float64
 7   colonia_solicitud        str
 8   alcaldia_solicitud       float64
 9   codigo_postal_solicitud  str
 10  estatus                  str
 11  fecha_concluido          str
 12  latitud                  float64
 13  longitud                 float64
dtypes: float64(4), int64(1), str(9)
memory usage: 464.5 MB

In [96]:
df_complete.nunique(dropna=True)

id_folio                   2303176
fecha_solicitud               1208
hora_solicitud              572941
tipo_de_entrada                 10
tema_solicitud                  72
sexo                             4
edad                           105
colonia_solicitud             1925
alcaldia_solicitud              16
codigo_postal_solicitud       4146
estatus                          5
fecha_concluido               1207
latitud                     900812
longitud                    853156
dtype: int64

In [97]:
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,edad,colonia_solicitud,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,latitud,longitud
0,1751404,2023-01-11,10:35:26.541,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Autoridad Responsable,NaN,NaN,NaN
1,1752021,2023-01-11,12:45:18.413,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
2,1752656,2023-01-11,14:59:29.499,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
3,1752838,2023-01-11,16:39:57.5,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
4,1752915,2023-01-11,17:38:06.237,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7710.0,Cerrado,2023-01-18,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2303171,3938194,2026-02-10,11:26:54,Usuarios SUAC Dependencia,PODA,Femenino,NaN,NaN,NaN,08730,Cerrado,2026-02-10,NaN,NaN
2303172,3938459,2026-02-10,12:11:44,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,46.0,NaN,NaN,09720,Cerrado,2026-03-12,NaN,NaN
2303173,3938818,2026-02-10,13:04:29,Portal Ciudadano SUAC,SOCAVÓN,Masculino,NaN,NaN,NaN,07080,Cerrado,2026-03-19,NaN,NaN
2303174,3938923,2026-02-10,13:19:40,Operador Telefónico - Ventanilla,SERVICIOS DE SALUD,Femenino,58.0,NaN,NaN,NaN,Cerrado,2026-02-18,NaN,NaN
2303175,3939023,2026-02-10,13:35:10,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,NaN,NaN,NaN,04300,Cerrado,2026-02-19,NaN,NaN

## Limpieza de Datos

### Manejo de Fechas y Horas

Transformar fecha_solicitud, fecha_concluido y hora_solicitud

In [98]:
df_complete['fecha_solicitud'] = pd.to_datetime(df_complete['fecha_solicitud'], format='%Y-%m-%d')
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,edad,colonia_solicitud,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,latitud,longitud
0,1751404,2023-01-11,10:35:26.541,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Autoridad Responsable,NaN,NaN,NaN
1,1752021,2023-01-11,12:45:18.413,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
2,1752656,2023-01-11,14:59:29.499,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
3,1752838,2023-01-11,16:39:57.5,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
4,1752915,2023-01-11,17:38:06.237,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7710.0,Cerrado,2023-01-18,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2303171,3938194,2026-02-10,11:26:54,Usuarios SUAC Dependencia,PODA,Femenino,NaN,NaN,NaN,08730,Cerrado,2026-02-10,NaN,NaN
2303172,3938459,2026-02-10,12:11:44,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,46.0,NaN,NaN,09720,Cerrado,2026-03-12,NaN,NaN
2303173,3938818,2026-02-10,13:04:29,Portal Ciudadano SUAC,SOCAVÓN,Masculino,NaN,NaN,NaN,07080,Cerrado,2026-03-19,NaN,NaN
2303174,3938923,2026-02-10,13:19:40,Operador Telefónico - Ventanilla,SERVICIOS DE SALUD,Femenino,58.0,NaN,NaN,NaN,Cerrado,2026-02-18,NaN,NaN
2303175,3939023,2026-02-10,13:35:10,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,NaN,NaN,NaN,04300,Cerrado,2026-02-19,NaN,NaN

In [99]:
df_complete['fecha_concluido'] = pd.to_datetime(df_complete['fecha_concluido'], format='%Y-%m-%d')
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,edad,colonia_solicitud,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,latitud,longitud
0,1751404,2023-01-11,10:35:26.541,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Autoridad Responsable,NaT,NaN,NaN
1,1752021,2023-01-11,12:45:18.413,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
2,1752656,2023-01-11,14:59:29.499,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
3,1752838,2023-01-11,16:39:57.5,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
4,1752915,2023-01-11,17:38:06.237,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7710.0,Cerrado,2023-01-18,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2303171,3938194,2026-02-10,11:26:54,Usuarios SUAC Dependencia,PODA,Femenino,NaN,NaN,NaN,08730,Cerrado,2026-02-10,NaN,NaN
2303172,3938459,2026-02-10,12:11:44,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,46.0,NaN,NaN,09720,Cerrado,2026-03-12,NaN,NaN
2303173,3938818,2026-02-10,13:04:29,Portal Ciudadano SUAC,SOCAVÓN,Masculino,NaN,NaN,NaN,07080,Cerrado,2026-03-19,NaN,NaN
2303174,3938923,2026-02-10,13:19:40,Operador Telefónico - Ventanilla,SERVICIOS DE SALUD,Femenino,58.0,NaN,NaN,NaN,Cerrado,2026-02-18,NaN,NaN
2303175,3939023,2026-02-10,13:35:10,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,NaN,NaN,NaN,04300,Cerrado,2026-02-19,NaN,NaN

In [100]:
df_complete['hora_solicitud'] = pd.to_datetime(df_complete['hora_solicitud'], format='mixed', errors='coerce').dt.hour
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,edad,colonia_solicitud,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,latitud,longitud
0,1751404,2023-01-11,10,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Autoridad Responsable,NaT,NaN,NaN
1,1752021,2023-01-11,12,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
2,1752656,2023-01-11,14,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
3,1752838,2023-01-11,16,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN
4,1752915,2023-01-11,17,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7710.0,Cerrado,2023-01-18,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2303171,3938194,2026-02-10,11,Usuarios SUAC Dependencia,PODA,Femenino,NaN,NaN,NaN,08730,Cerrado,2026-02-10,NaN,NaN
2303172,3938459,2026-02-10,12,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,46.0,NaN,NaN,09720,Cerrado,2026-03-12,NaN,NaN
2303173,3938818,2026-02-10,13,Portal Ciudadano SUAC,SOCAVÓN,Masculino,NaN,NaN,NaN,07080,Cerrado,2026-03-19,NaN,NaN
2303174,3938923,2026-02-10,13,Operador Telefónico - Ventanilla,SERVICIOS DE SALUD,Femenino,58.0,NaN,NaN,NaN,Cerrado,2026-02-18,NaN,NaN
2303175,3939023,2026-02-10,13,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,NaN,NaN,NaN,04300,Cerrado,2026-02-19,NaN,NaN

#### Variabel Objetivo

In [101]:
df_complete['tiempo_resolución'] = (df_complete['fecha_concluido'] - df_complete['fecha_solicitud']).dt.total_seconds() / 86400
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,edad,colonia_solicitud,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,latitud,longitud,tiempo_resolución
0,1751404,2023-01-11,10,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Autoridad Responsable,NaT,NaN,NaN,NaN
1,1752021,2023-01-11,12,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN,7.0
2,1752656,2023-01-11,14,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN,7.0
3,1752838,2023-01-11,16,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN,7.0
4,1752915,2023-01-11,17,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7710.0,Cerrado,2023-01-18,NaN,NaN,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2303171,3938194,2026-02-10,11,Usuarios SUAC Dependencia,PODA,Femenino,NaN,NaN,NaN,08730,Cerrado,2026-02-10,NaN,NaN,0.0
2303172,3938459,2026-02-10,12,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,46.0,NaN,NaN,09720,Cerrado,2026-03-12,NaN,NaN,30.0
2303173,3938818,2026-02-10,13,Portal Ciudadano SUAC,SOCAVÓN,Masculino,NaN,NaN,NaN,07080,Cerrado,2026-03-19,NaN,NaN,37.0
2303174,3938923,2026-02-10,13,Operador Telefónico - Ventanilla,SERVICIOS DE SALUD,Femenino,58.0,NaN,NaN,NaN,Cerrado,2026-02-18,NaN,NaN,8.0
2303175,3939023,2026-02-10,13,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,NaN,NaN,NaN,04300,Cerrado,2026-02-19,NaN,NaN,9.0

In [102]:
df_complete['dia_solicitud'] = df_complete['fecha_solicitud'].dt.day_name()
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,edad,colonia_solicitud,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,latitud,longitud,tiempo_resolución,dia_solicitud
0,1751404,2023-01-11,10,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Autoridad Responsable,NaT,NaN,NaN,NaN,Wednesday
1,1752021,2023-01-11,12,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN,7.0,Wednesday
2,1752656,2023-01-11,14,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN,7.0,Wednesday
3,1752838,2023-01-11,16,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7700.0,Cerrado,2023-01-18,NaN,NaN,7.0,Wednesday
4,1752915,2023-01-11,17,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,NaN,NUEVA INDUSTRIAL VALLEJO,5.0,7710.0,Cerrado,2023-01-18,NaN,NaN,7.0,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2303171,3938194,2026-02-10,11,Usuarios SUAC Dependencia,PODA,Femenino,NaN,NaN,NaN,08730,Cerrado,2026-02-10,NaN,NaN,0.0,Tuesday
2303172,3938459,2026-02-10,12,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,46.0,NaN,NaN,09720,Cerrado,2026-03-12,NaN,NaN,30.0,Tuesday
2303173,3938818,2026-02-10,13,Portal Ciudadano SUAC,SOCAVÓN,Masculino,NaN,NaN,NaN,07080,Cerrado,2026-03-19,NaN,NaN,37.0,Tuesday
2303174,3938923,2026-02-10,13,Operador Telefónico - Ventanilla,SERVICIOS DE SALUD,Femenino,58.0,NaN,NaN,NaN,Cerrado,2026-02-18,NaN,NaN,8.0,Tuesday
2303175,3939023,2026-02-10,13,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,NaN,NaN,NaN,04300,Cerrado,2026-02-19,NaN,NaN,9.0,Tuesday

In [103]:
df_complete.isnull().mean()*100

id_folio                    0.000000
fecha_solicitud             0.000000
hora_solicitud              0.000000
tipo_de_entrada             0.000000
tema_solicitud              0.000000
sexo                       10.972805
edad                       87.416724
colonia_solicitud          49.869528
alcaldia_solicitud         49.869528
codigo_postal_solicitud     4.147621
estatus                     0.000000
fecha_concluido             6.094714
latitud                    57.139272
longitud                   60.680295
tiempo_resolución           6.094714
dia_solicitud               0.000000
dtype: float64

Eliminar columnas con +40% nulos (no se elimina alcaldía porque se imputará más adelante con CP)

In [104]:
columnas_nulos = ['edad','colonia_solicitud','latitud','longitud']
df_complete.drop(labels=columnas_nulos, axis=1,inplace=True)
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,tiempo_resolución,dia_solicitud
0,1751404,2023-01-11,10,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Autoridad Responsable,NaT,NaN,Wednesday
1,1752021,2023-01-11,12,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,7.0,Wednesday
2,1752656,2023-01-11,14,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,7.0,Wednesday
3,1752838,2023-01-11,16,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,7.0,Wednesday
4,1752915,2023-01-11,17,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7710.0,Cerrado,2023-01-18,7.0,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...
2303171,3938194,2026-02-10,11,Usuarios SUAC Dependencia,PODA,Femenino,NaN,08730,Cerrado,2026-02-10,0.0,Tuesday
2303172,3938459,2026-02-10,12,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,NaN,09720,Cerrado,2026-03-12,30.0,Tuesday
2303173,3938818,2026-02-10,13,Portal Ciudadano SUAC,SOCAVÓN,Masculino,NaN,07080,Cerrado,2026-03-19,37.0,Tuesday
2303174,3938923,2026-02-10,13,Operador Telefónico - Ventanilla,SERVICIOS DE SALUD,Femenino,NaN,NaN,Cerrado,2026-02-18,8.0,Tuesday
2303175,3939023,2026-02-10,13,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,NaN,04300,Cerrado,2026-02-19,9.0,Tuesday

In [105]:
df_complete.isnull().mean()*100

id_folio                    0.000000
fecha_solicitud             0.000000
hora_solicitud              0.000000
tipo_de_entrada             0.000000
tema_solicitud              0.000000
sexo                       10.972805
alcaldia_solicitud         49.869528
codigo_postal_solicitud     4.147621
estatus                     0.000000
fecha_concluido             6.094714
tiempo_resolución           6.094714
dia_solicitud               0.000000
dtype: float64

Imputar alcaldía con CP

In [106]:
zip_codes = "../data/raw/CodigosPostales.csv"
df_zp = pd.read_csv(zip_codes, usecols=['Código Postal','Municipio','Ciudad'],header=1)
df_zp

      Código Postal              Municipio            Ciudad
0              1857         Álvaro Obregón  Ciudad de México
1              1859         Álvaro Obregón  Ciudad de México
2              1860         Álvaro Obregón  Ciudad de México
3              1863         Álvaro Obregón  Ciudad de México
4              1870         Álvaro Obregón  Ciudad de México
...             ...                    ...               ...
1525           5220  Cuajimalpa de Morelos  Ciudad de México
1526           5230  Cuajimalpa de Morelos  Ciudad de México
1527           5240  Cuajimalpa de Morelos  Ciudad de México
1528           5260  Cuajimalpa de Morelos  Ciudad de México
1529           5269  Cuajimalpa de Morelos  Ciudad de México

[1530 rows x 3 columns]

In [107]:
df_zp.info()

<class 'pandas.DataFrame'>
RangeIndex: 1530 entries, 0 to 1529
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Código Postal  1530 non-null   int64
 1   Municipio      1530 non-null   str
 2   Ciudad         1529 non-null   str
dtypes: int64(1), str(2)
memory usage: 80.6 KB

Add 0 to Zip Code strings

In [108]:
df_zp['Código Postal'] = df_zp['Código Postal'].apply(lambda x: str(x).zfill(5) if pd.notna(x) else x)
df_zp

     Código Postal              Municipio            Ciudad
0            01857         Álvaro Obregón  Ciudad de México
1            01859         Álvaro Obregón  Ciudad de México
2            01860         Álvaro Obregón  Ciudad de México
3            01863         Álvaro Obregón  Ciudad de México
4            01870         Álvaro Obregón  Ciudad de México
...            ...                    ...               ...
1525         05220  Cuajimalpa de Morelos  Ciudad de México
1526         05230  Cuajimalpa de Morelos  Ciudad de México
1527         05240  Cuajimalpa de Morelos  Ciudad de México
1528         05260  Cuajimalpa de Morelos  Ciudad de México
1529         05269  Cuajimalpa de Morelos  Ciudad de México

[1530 rows x 3 columns]

In [109]:
df_complete.info()

<class 'pandas.DataFrame'>
RangeIndex: 2303176 entries, 0 to 2303175
Data columns (total 12 columns):
 #   Column                   Dtype
---  ------                   -----
 0   id_folio                 int64
 1   fecha_solicitud          datetime64[us]
 2   hora_solicitud           int32
 3   tipo_de_entrada          str
 4   tema_solicitud           str
 5   sexo                     str
 6   alcaldia_solicitud       float64
 7   codigo_postal_solicitud  str
 8   estatus                  str
 9   fecha_concluido          datetime64[us]
 10  tiempo_resolución        float64
 11  dia_solicitud            str
dtypes: datetime64[us](2), float64(2), int32(1), int64(1), str(6)
memory usage: 356.6 MB

In [110]:
mask = df_complete['codigo_postal_solicitud'].apply(
    lambda x: pd.notna(x) and str(x).strip() != '' and not str(x).strip().replace('.','',1).isdigit()
)
df_complete.loc[mask, 'codigo_postal_solicitud'].value_counts()

codigo_postal_solicitud
-1       149541
-1        42801
-1.0       2130
Otro          5
0436*         1
0860T         1
10O10         1
0r369         1
08wf          1
54 02         1
Name: count, dtype: int64

In [111]:
df_complete.loc[mask, 'codigo_postal_solicitud'] \
    .apply(lambda x: (type(x).__name__, repr(x))) \
    .value_counts()

codigo_postal_solicitud
(str, '-1   ')    149541
(str, '-1')        42801
(str, '-1.0')       2130
(str, 'Otro ')         5
(str, '0436*')         1
(str, '0860T')         1
(str, '10O10')         1
(str, '0r369')         1
(str, '08wf ')         1
(str, '54 02')         1
Name: count, dtype: int64

In [112]:
invalid_zc = ['-1   ','-1','-1.0','Otro ','0436*','0860T','10O10','0r369','08wf ','54 02']
#df_complete['codigo_postal_solicitud'] = df_complete['codigo_postal_solicitud'].replace(invalid_zc, 'Desconocido')
df_complete = df_complete[~df_complete['codigo_postal_solicitud'].isin(invalid_zc)]
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,tiempo_resolución,dia_solicitud
0,1751404,2023-01-11,10,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Autoridad Responsable,NaT,NaN,Wednesday
1,1752021,2023-01-11,12,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,7.0,Wednesday
2,1752656,2023-01-11,14,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,7.0,Wednesday
3,1752838,2023-01-11,16,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7700.0,Cerrado,2023-01-18,7.0,Wednesday
4,1752915,2023-01-11,17,Portal Ciudadano SUAC,FALTA DE AGUA,NaN,5.0,7710.0,Cerrado,2023-01-18,7.0,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...
2303171,3938194,2026-02-10,11,Usuarios SUAC Dependencia,PODA,Femenino,NaN,08730,Cerrado,2026-02-10,0.0,Tuesday
2303172,3938459,2026-02-10,12,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,NaN,09720,Cerrado,2026-03-12,30.0,Tuesday
2303173,3938818,2026-02-10,13,Portal Ciudadano SUAC,SOCAVÓN,Masculino,NaN,07080,Cerrado,2026-03-19,37.0,Tuesday
2303174,3938923,2026-02-10,13,Operador Telefónico - Ventanilla,SERVICIOS DE SALUD,Femenino,NaN,NaN,Cerrado,2026-02-18,8.0,Tuesday
2303175,3939023,2026-02-10,13,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,NaN,04300,Cerrado,2026-02-19,9.0,Tuesday

In [113]:
df_complete.isnull().mean()*100

id_folio                    0.000000
fecha_solicitud             0.000000
hora_solicitud              0.000000
tipo_de_entrada             0.000000
tema_solicitud              0.000000
sexo                       11.984817
alcaldia_solicitud         54.467815
codigo_postal_solicitud     4.530152
estatus                     0.000000
fecha_concluido             6.505594
tiempo_resolución           6.505594
dia_solicitud               0.000000
dtype: float64

Imputar datos faltantes de sexo y como nueva categoría "No especificado"

In [114]:
df_complete[['sexo']] = df_complete[['sexo']].fillna('No especificado')
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,tiempo_resolución,dia_solicitud
0,1751404,2023-01-11,10,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,5.0,7700.0,Autoridad Responsable,NaT,NaN,Wednesday
1,1752021,2023-01-11,12,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,5.0,7700.0,Cerrado,2023-01-18,7.0,Wednesday
2,1752656,2023-01-11,14,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,5.0,7700.0,Cerrado,2023-01-18,7.0,Wednesday
3,1752838,2023-01-11,16,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,5.0,7700.0,Cerrado,2023-01-18,7.0,Wednesday
4,1752915,2023-01-11,17,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,5.0,7710.0,Cerrado,2023-01-18,7.0,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...
2303171,3938194,2026-02-10,11,Usuarios SUAC Dependencia,PODA,Femenino,NaN,08730,Cerrado,2026-02-10,0.0,Tuesday
2303172,3938459,2026-02-10,12,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,NaN,09720,Cerrado,2026-03-12,30.0,Tuesday
2303173,3938818,2026-02-10,13,Portal Ciudadano SUAC,SOCAVÓN,Masculino,NaN,07080,Cerrado,2026-03-19,37.0,Tuesday
2303174,3938923,2026-02-10,13,Operador Telefónico - Ventanilla,SERVICIOS DE SALUD,Femenino,NaN,NaN,Cerrado,2026-02-18,8.0,Tuesday
2303175,3939023,2026-02-10,13,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,NaN,04300,Cerrado,2026-02-19,9.0,Tuesday

In [115]:
df_complete.isnull().mean()*100

id_folio                    0.000000
fecha_solicitud             0.000000
hora_solicitud              0.000000
tipo_de_entrada             0.000000
tema_solicitud              0.000000
sexo                        0.000000
alcaldia_solicitud         54.467815
codigo_postal_solicitud     4.530152
estatus                     0.000000
fecha_concluido             6.505594
tiempo_resolución           6.505594
dia_solicitud               0.000000
dtype: float64

In [116]:
df_complete.dropna(subset=['codigo_postal_solicitud'],inplace=True)
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,tiempo_resolución,dia_solicitud
0,1751404,2023-01-11,10,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,5.0,7700.0,Autoridad Responsable,NaT,NaN,Wednesday
1,1752021,2023-01-11,12,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,5.0,7700.0,Cerrado,2023-01-18,7.0,Wednesday
2,1752656,2023-01-11,14,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,5.0,7700.0,Cerrado,2023-01-18,7.0,Wednesday
3,1752838,2023-01-11,16,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,5.0,7700.0,Cerrado,2023-01-18,7.0,Wednesday
4,1752915,2023-01-11,17,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,5.0,7710.0,Cerrado,2023-01-18,7.0,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...
2303169,3937609,2026-02-10,9,Usuarios SUAC Dependencia,DESAZOLVE,Masculino,NaN,08000,Cerrado,2026-02-10,0.0,Tuesday
2303171,3938194,2026-02-10,11,Usuarios SUAC Dependencia,PODA,Femenino,NaN,08730,Cerrado,2026-02-10,0.0,Tuesday
2303172,3938459,2026-02-10,12,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,NaN,09720,Cerrado,2026-03-12,30.0,Tuesday
2303173,3938818,2026-02-10,13,Portal Ciudadano SUAC,SOCAVÓN,Masculino,NaN,07080,Cerrado,2026-03-19,37.0,Tuesday
2303175,3939023,2026-02-10,13,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,NaN,04300,Cerrado,2026-02-19,9.0,Tuesday

In [117]:
df_complete.isnull().mean()*100

id_folio                    0.000000
fecha_solicitud             0.000000
hora_solicitud              0.000000
tipo_de_entrada             0.000000
tema_solicitud              0.000000
sexo                        0.000000
alcaldia_solicitud         52.332346
codigo_postal_solicitud     0.000000
estatus                     0.000000
fecha_concluido             6.725128
tiempo_resolución           6.725128
dia_solicitud               0.000000
dtype: float64

In [118]:
patterns = df_complete['codigo_postal_solicitud'].dropna().apply(
    lambda x: ''.join(['d' if c.isdigit() else ('a' if c.isalpha() else c) for c in str(x).strip()])
)
patterns.value_counts()

codigo_postal_solicitud
ddddd      1749419
dddd        140598
dddd.d       95612
ddddd.d      26417
              1057
d               22
d.d             14
dd              13
ddd             10
dd.dd            2
ddd.d            1
dddd.            1
Name: count, dtype: int64

In [119]:
def clean_cp(x):
    if pd.isna(x):
        return None
    x = str(x).strip().rstrip('.')
    if x == '':
        return None
    try:
        result = str(int(float(x))).zfill(5)
        if len(result) > 5 or int(result) < 1000:
            return None
        return result
    except ValueError:
        return None

In [120]:
df_complete['codigo_postal_solicitud'] = df_complete['codigo_postal_solicitud'].apply(clean_cp)

In [121]:
patterns = df_complete['codigo_postal_solicitud'].dropna().apply(
    lambda x: ''.join(['d' if c.isdigit() else ('a' if c.isalpha() else c) for c in str(x).strip()])
)
patterns.value_counts()

codigo_postal_solicitud
ddddd    2011738
Name: count, dtype: int64

In [122]:
df_zp_cdmx = df_zp.where(df_zp['Ciudad'] == 'Ciudad de México')
df_zp_cdmx['Municipio'].value_counts()

Municipio
Álvaro Obregón            222
Iztapalapa                199
Gustavo A. Madero         177
Tlalpan                   158
Xochimilco                111
Coyoacán                   96
Azcapotzalco               88
Miguel Hidalgo             86
Tláhuac                    71
Venustiano Carranza        67
Benito Juárez              53
Cuajimalpa de Morelos      46
Cuauhtémoc                 41
La Magdalena Contreras     41
Iztacalco                  38
Milpa Alta                 35
Name: count, dtype: int64

### Imputar CP en alcaldías

In [123]:
df_complete['alcaldia_solicitud'].value_counts()

alcaldia_solicitud
7.0     215137
5.0     103118
15.0     95261
3.0      82492
12.0     76367
10.0     65694
14.0     55889
2.0      53566
13.0     46104
6.0      42685
16.0     34410
17.0     24108
11.0     19645
8.0      18093
4.0      15140
9.0      11920
Name: count, dtype: int64

In [124]:
alcaldías = {2.0:'Azcapotzalco',3.0:'Coyoacán',4.0:'Cuajimalpa de Morelos',5.0:'Gustavo A. Madero',6.0:'Iztacalco',7.0:'Iztapalapa',8.0:'La Magdalena Contreras',
9.0:'Milpa Alta',10.0:'Álvaro Obregón',11.0:'Tláhuac',12.0:'Tlalpan',13.0:'Xochimilco',14.0:'Benito Juárez',15.0:'Cuauhtémoc',16.0:'Miguel Hidalgo',
17.0:'Venustiano Carranza'}

In [125]:
df_zp_cdmx

     Código Postal              Municipio            Ciudad
0            01857         Álvaro Obregón  Ciudad de México
1            01859         Álvaro Obregón  Ciudad de México
2            01860         Álvaro Obregón  Ciudad de México
3            01863         Álvaro Obregón  Ciudad de México
4            01870         Álvaro Obregón  Ciudad de México
...            ...                    ...               ...
1525         05220  Cuajimalpa de Morelos  Ciudad de México
1526         05230  Cuajimalpa de Morelos  Ciudad de México
1527         05240  Cuajimalpa de Morelos  Ciudad de México
1528         05260  Cuajimalpa de Morelos  Ciudad de México
1529         05269  Cuajimalpa de Morelos  Ciudad de México

[1530 rows x 3 columns]

In [126]:
df_complete['alcaldia_solicitud'] = df_complete['alcaldia_solicitud'].map(alcaldías)
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,tiempo_resolución,dia_solicitud
0,1751404,2023-01-11,10,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07700,Autoridad Responsable,NaT,NaN,Wednesday
1,1752021,2023-01-11,12,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07700,Cerrado,2023-01-18,7.0,Wednesday
2,1752656,2023-01-11,14,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07700,Cerrado,2023-01-18,7.0,Wednesday
3,1752838,2023-01-11,16,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07700,Cerrado,2023-01-18,7.0,Wednesday
4,1752915,2023-01-11,17,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07710,Cerrado,2023-01-18,7.0,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...
2303169,3937609,2026-02-10,9,Usuarios SUAC Dependencia,DESAZOLVE,Masculino,NaN,08000,Cerrado,2026-02-10,0.0,Tuesday
2303171,3938194,2026-02-10,11,Usuarios SUAC Dependencia,PODA,Femenino,NaN,08730,Cerrado,2026-02-10,0.0,Tuesday
2303172,3938459,2026-02-10,12,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,NaN,09720,Cerrado,2026-03-12,30.0,Tuesday
2303173,3938818,2026-02-10,13,Portal Ciudadano SUAC,SOCAVÓN,Masculino,NaN,07080,Cerrado,2026-03-19,37.0,Tuesday
2303175,3939023,2026-02-10,13,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,NaN,04300,Cerrado,2026-02-19,9.0,Tuesday

In [127]:
df_complete['alcaldia_solicitud'].value_counts()

alcaldia_solicitud
Iztapalapa                215137
Gustavo A. Madero         103118
Cuauhtémoc                 95261
Coyoacán                   82492
Tlalpan                    76367
Álvaro Obregón             65694
Benito Juárez              55889
Azcapotzalco               53566
Xochimilco                 46104
Iztacalco                  42685
Miguel Hidalgo             34410
Venustiano Carranza        24108
Tláhuac                    19645
La Magdalena Contreras     18093
Cuajimalpa de Morelos      15140
Milpa Alta                 11920
Name: count, dtype: int64

In [128]:
alcaldia_cp = {
    '01':'Álvaro Obregón',
    '02':'Azcapotzalco',
    '03':'Benito Juárez',
    '04':'Coyoacán',
    '05':'Cuajimalpa de Morelos',
    '06':'Cuauhtémoc',
    '07':'Gustavo A. Madero',
    '08':'Iztacalco',
    '09':'Iztapalapa',
    '10':'La Magdalena Contreras',
    '11':'Miguel Hidalgo',
    '12':'Milpa Alta',
    '13':'Tláhuac',
    '14':'Tlalpan',
    '15':'Venustiano Carranza',
    '16':'Xochimilco'
}

In [129]:
missing_mask = df_complete['alcaldia_solicitud'].isna()

df_complete.loc[missing_mask, 'alcaldia_solicitud'] = (
    df_complete.loc[missing_mask, 'codigo_postal_solicitud']
    .astype(str)
    .str[:2]
    .map(alcaldia_cp)
)

In [130]:
#df_complete = df_complete.merge(
#    df_zp_cdmx[['Código Postal','Municipio']], 
#    how='left', 
#    left_on='codigo_postal_solicitud', 
#    right_on='Código Postal'
#    )
#df_complete

In [131]:
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,tiempo_resolución,dia_solicitud
0,1751404,2023-01-11,10,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07700,Autoridad Responsable,NaT,NaN,Wednesday
1,1752021,2023-01-11,12,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07700,Cerrado,2023-01-18,7.0,Wednesday
2,1752656,2023-01-11,14,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07700,Cerrado,2023-01-18,7.0,Wednesday
3,1752838,2023-01-11,16,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07700,Cerrado,2023-01-18,7.0,Wednesday
4,1752915,2023-01-11,17,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07710,Cerrado,2023-01-18,7.0,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...
2303169,3937609,2026-02-10,9,Usuarios SUAC Dependencia,DESAZOLVE,Masculino,Iztacalco,08000,Cerrado,2026-02-10,0.0,Tuesday
2303171,3938194,2026-02-10,11,Usuarios SUAC Dependencia,PODA,Femenino,Iztacalco,08730,Cerrado,2026-02-10,0.0,Tuesday
2303172,3938459,2026-02-10,12,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,Iztapalapa,09720,Cerrado,2026-03-12,30.0,Tuesday
2303173,3938818,2026-02-10,13,Portal Ciudadano SUAC,SOCAVÓN,Masculino,Gustavo A. Madero,07080,Cerrado,2026-03-19,37.0,Tuesday
2303175,3939023,2026-02-10,13,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,Coyoacán,04300,Cerrado,2026-02-19,9.0,Tuesday

In [132]:
df_complete.isnull().mean()

id_folio                   0.000000
fecha_solicitud            0.000000
hora_solicitud             0.000000
tipo_de_entrada            0.000000
tema_solicitud             0.000000
sexo                       0.000000
alcaldia_solicitud         0.000855
codigo_postal_solicitud    0.000709
estatus                    0.000000
fecha_concluido            0.067251
tiempo_resolución          0.067251
dia_solicitud              0.000000
dtype: float64

In [133]:
df_complete.dropna(subset=['alcaldia_solicitud','codigo_postal_solicitud','tiempo_resolución'],inplace=True)
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,tiempo_resolución,dia_solicitud
1,1752021,2023-01-11,12,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07700,Cerrado,2023-01-18,7.0,Wednesday
2,1752656,2023-01-11,14,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07700,Cerrado,2023-01-18,7.0,Wednesday
3,1752838,2023-01-11,16,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07700,Cerrado,2023-01-18,7.0,Wednesday
4,1752915,2023-01-11,17,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07710,Cerrado,2023-01-18,7.0,Wednesday
5,1753053,2023-01-11,19,Portal Ciudadano SUAC,SOLICITUD DE VIGILANCIA POLICIACA,No especificado,Gustavo A. Madero,07000,Cerrado,2023-01-18,7.0,Wednesday
...,...,...,...,...,...,...,...,...,...,...,...,...
2303169,3937609,2026-02-10,9,Usuarios SUAC Dependencia,DESAZOLVE,Masculino,Iztacalco,08000,Cerrado,2026-02-10,0.0,Tuesday
2303171,3938194,2026-02-10,11,Usuarios SUAC Dependencia,PODA,Femenino,Iztacalco,08730,Cerrado,2026-02-10,0.0,Tuesday
2303172,3938459,2026-02-10,12,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,Iztapalapa,09720,Cerrado,2026-03-12,30.0,Tuesday
2303173,3938818,2026-02-10,13,Portal Ciudadano SUAC,SOCAVÓN,Masculino,Gustavo A. Madero,07080,Cerrado,2026-03-19,37.0,Tuesday
2303175,3939023,2026-02-10,13,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,Coyoacán,04300,Cerrado,2026-02-19,9.0,Tuesday

In [134]:
df_complete['mes_solicitud'] = df_complete['fecha_solicitud'].dt.month_name()
df_complete

,id_folio,fecha_solicitud,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,codigo_postal_solicitud,estatus,fecha_concluido,tiempo_resolución,dia_solicitud,mes_solicitud
1,1752021,2023-01-11,12,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07700,Cerrado,2023-01-18,7.0,Wednesday,January
2,1752656,2023-01-11,14,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07700,Cerrado,2023-01-18,7.0,Wednesday,January
3,1752838,2023-01-11,16,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07700,Cerrado,2023-01-18,7.0,Wednesday,January
4,1752915,2023-01-11,17,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07710,Cerrado,2023-01-18,7.0,Wednesday,January
5,1753053,2023-01-11,19,Portal Ciudadano SUAC,SOLICITUD DE VIGILANCIA POLICIACA,No especificado,Gustavo A. Madero,07000,Cerrado,2023-01-18,7.0,Wednesday,January
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2303169,3937609,2026-02-10,9,Usuarios SUAC Dependencia,DESAZOLVE,Masculino,Iztacalco,08000,Cerrado,2026-02-10,0.0,Tuesday,February
2303171,3938194,2026-02-10,11,Usuarios SUAC Dependencia,PODA,Femenino,Iztacalco,08730,Cerrado,2026-02-10,0.0,Tuesday,February
2303172,3938459,2026-02-10,12,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,Iztapalapa,09720,Cerrado,2026-03-12,30.0,Tuesday,February
2303173,3938818,2026-02-10,13,Portal Ciudadano SUAC,SOCAVÓN,Masculino,Gustavo A. Madero,07080,Cerrado,2026-03-19,37.0,Tuesday,February
2303175,3939023,2026-02-10,13,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,Coyoacán,04300,Cerrado,2026-02-19,9.0,Tuesday,February

In [135]:
df_complete.isnull().mean()

id_folio                   0.0
fecha_solicitud            0.0
hora_solicitud             0.0
tipo_de_entrada            0.0
tema_solicitud             0.0
sexo                       0.0
alcaldia_solicitud         0.0
codigo_postal_solicitud    0.0
estatus                    0.0
fecha_concluido            0.0
tiempo_resolución          0.0
dia_solicitud              0.0
mes_solicitud              0.0
dtype: float64

In [136]:
columnas_drop = ['id_folio','fecha_solicitud','estatus','fecha_concluido']
df_complete.drop(columns=columnas_drop,inplace=True)
df_complete

,hora_solicitud,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,codigo_postal_solicitud,tiempo_resolución,dia_solicitud,mes_solicitud
1,12,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07700,7.0,Wednesday,January
2,14,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07700,7.0,Wednesday,January
3,16,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07700,7.0,Wednesday,January
4,17,Portal Ciudadano SUAC,FALTA DE AGUA,No especificado,Gustavo A. Madero,07710,7.0,Wednesday,January
5,19,Portal Ciudadano SUAC,SOLICITUD DE VIGILANCIA POLICIACA,No especificado,Gustavo A. Madero,07000,7.0,Wednesday,January
...,...,...,...,...,...,...,...,...,...
2303169,9,Usuarios SUAC Dependencia,DESAZOLVE,Masculino,Iztacalco,08000,0.0,Tuesday,February
2303171,11,Usuarios SUAC Dependencia,PODA,Femenino,Iztacalco,08730,0.0,Tuesday,February
2303172,12,Operador Telefónico LOCATEL,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,Masculino,Iztapalapa,09720,30.0,Tuesday,February
2303173,13,Portal Ciudadano SUAC,SOCAVÓN,Masculino,Gustavo A. Madero,07080,37.0,Tuesday,February
2303175,13,Usuarios SUAC Dependencia,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,Coyoacán,04300,9.0,Tuesday,February

In [137]:
df_complete.isnull().mean()*100

hora_solicitud             0.0
tipo_de_entrada            0.0
tema_solicitud             0.0
sexo                       0.0
alcaldia_solicitud         0.0
codigo_postal_solicitud    0.0
tiempo_resolución          0.0
dia_solicitud              0.0
mes_solicitud              0.0
dtype: float64

In [138]:
df_complete['hora_sin'] = np.sin(2 * np.pi * df_complete['hora_solicitud'] / 24)
df_complete['hora_cos'] = np.cos(2 * np.pi * df_complete['hora_solicitud'] / 24)

In [139]:
df_complete.drop(columns=['hora_solicitud'], inplace=True)

## Visualizaciones

In [140]:
columns_df = df_complete.columns.to_list()
columns_df

['tipo_de_entrada',
 'tema_solicitud',
 'sexo',
 'alcaldia_solicitud',
 'codigo_postal_solicitud',
 'tiempo_resolución',
 'dia_solicitud',
 'mes_solicitud',
 'hora_sin',
 'hora_cos']

In [141]:
for param in columns_df:
    param_values = df_complete[param].value_counts()
    fig = px.histogram(x=param_values.index,y=param_values.values,nbins=len(param_values.index))
    fig.update_layout(xaxis_title=f'{param}', yaxis_title='Cantidad')
    fig.show()

## Data Splitting

In [142]:
X = df_complete.drop(columns=['tiempo_resolución'])
y = df_complete['tiempo_resolución']

In [143]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

## Codificación

In [144]:
X_train.info()

<class 'pandas.DataFrame'>
Index: 1500787 entries, 574289 to 129258
Data columns (total 9 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   tipo_de_entrada          1500787 non-null  str
 1   tema_solicitud           1500787 non-null  str
 2   sexo                     1500787 non-null  str
 3   alcaldia_solicitud       1500787 non-null  str
 4   codigo_postal_solicitud  1500787 non-null  str
 5   dia_solicitud            1500787 non-null  str
 6   mes_solicitud            1500787 non-null  str
 7   hora_sin                 1500787 non-null  float64
 8   hora_cos                 1500787 non-null  float64
dtypes: float64(2), str(7)
memory usage: 234.5 MB

In [145]:
conteo_tema = X_train['tema_solicitud'].value_counts(normalize=True)
conteo_tema

tema_solicitud
OTRO                                                      0.183187
FALTA DE AGUA                                             0.112674
REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO           0.105251
PODA                                                      0.086303
FUGA DE AGUA                                              0.072120
                                                            ...
ASISTENCIA SOCIAL / SITUACIÓN DE MOVILIDAD (MIGRANTES)    0.000024
COMEDORES COMUNITARIOS / PÚBLICOS                         0.000015
INFORMACIÓN, PROGRAMAS Y EVENTOS PARA JÓVENES             0.000013
RECICLAJE                                                 0.000011
JORNADAS NOTARIALES                                       0.000009
Name: proportion, Length: 72, dtype: float64

In [146]:
frecuencia_acumulada = conteo_tema.drop(labels='OTRO').cumsum()
frecuencia_acumulada

tema_solicitud
FALTA DE AGUA                                             0.112674
REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO           0.217924
PODA                                                      0.304228
FUGA DE AGUA                                              0.376348
BACHEO                                                    0.435554
                                                            ...
ASISTENCIA SOCIAL / SITUACIÓN DE MOVILIDAD (MIGRANTES)    0.816765
COMEDORES COMUNITARIOS / PÚBLICOS                         0.816780
INFORMACIÓN, PROGRAMAS Y EVENTOS PARA JÓVENES             0.816793
RECICLAJE                                                 0.816804
JORNADAS NOTARIALES                                       0.816813
Name: proportion, Length: 71, dtype: float64

In [147]:
top_categorias = frecuencia_acumulada.where(frecuencia_acumulada <= 0.8).dropna().index.to_list()
top_categorias

['FALTA DE AGUA',
 'REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO',
 'PODA',
 'FUGA DE AGUA',
 'BACHEO',
 'DESAZOLVE',
 'MANTENIMIENTO VÍA PÚBLICA',
 'SOLICITUD DE VIGILANCIA POLICIACA',
 'VERIFICACIÓN ADMINISTRATIVA',
 'RETIRO CASCAJO, ESCOMBRO, AZOLVE, RAMAS',
 'MANTENIMIENTO DE COLADERA / ALCANTARILLA',
 'VEHÍCULO ABANDONADO / CHATARRIZACIÓN',
 'QUEJA DE TRANSPORTE PÚBLICO',
 'BARBECHO / CHAPONEO',
 'MANTENIMIENTO DRENAJE',
 'RECOLECCIÓN BASURA',
 'LIMPIEZA VÍA PÚBLICA',
 'MANTENIMIENTO PARQUE / ÁREA VERDE',
 'PAVIMENTACIÓN / REENCARPETADO',
 'QUEJA SERVIDOR PÚBLICO',
 'MANTENIMIENTO DE BANQUETAS',
 'RETIRO AMBULANTE',
 'MANTENIMIENTO SEMÁFOROS',
 'PROTECCIÓN CIVIL',
 'RECUPERACIÓN DE VIALIDADES',
 'USO DE SUELO',
 'TRÁMITES / INFO MOVILIDAD',
 'SOLICITUD Y MANTENIMIENTO DE ALERTA SÍSMICA',
 'INFORMACIÓN DE TRÁMITES',
 'ASESORÍA Y CONSEJERÍA JURÍDICA Y LEGAL',
 'BALIZAMIENTO / REDUCTORES DE VELOCIDAD',
 'SOLICITUD DE PIPA DE AGUA',
 'SOLICITUD Y MANTENIMIENTO DE CÁMARAS DE VIGILANCIA',
 'VENTA DE ALCOHOL / DROGA']

In [148]:
X_train['tema_solicitud_compacto'] = X_train['tema_solicitud'].where(X_train['tema_solicitud'].isin(top_categorias),other='OTRO')
print(X_train['tema_solicitud_compacto'].value_counts(normalize=True).cumsum())

tema_solicitud_compacto
OTRO                                                  0.201147
FALTA DE AGUA                                         0.313821
REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO       0.419071
PODA                                                  0.505375
FUGA DE AGUA                                          0.577495
BACHEO                                                0.636701
DESAZOLVE                                             0.692908
MANTENIMIENTO VÍA PÚBLICA                             0.729387
SOLICITUD DE VIGILANCIA POLICIACA                     0.754934
VERIFICACIÓN ADMINISTRATIVA                           0.780330
RETIRO CASCAJO, ESCOMBRO, AZOLVE, RAMAS               0.804437
MANTENIMIENTO DE COLADERA / ALCANTARILLA              0.828103
VEHÍCULO ABANDONADO / CHATARRIZACIÓN                  0.851599
QUEJA DE TRANSPORTE PÚBLICO                           0.868127
BARBECHO / CHAPONEO                                   0.883452
MANTENIMIENTO DRENAJE                                 0.897294
RECOLECCIÓN BASURA                                    0.910494
LIMPIEZA VÍA PÚBLICA                                  0.922956
MANTENIMIENTO PARQUE / ÁREA VERDE                     0.932683
PAVIMENTACIÓN / REENCARPETADO                         0.941746
QUEJA SERVIDOR PÚBLICO                                0.948776
MANTENIMIENTO DE BANQUETAS                            0.954934
RETIRO AMBULANTE                                      0.960685
MANTENIMIENTO SEMÁFOROS                               0.965889
PROTECCIÓN CIVIL                                      0.970637
RECUPERACIÓN DE VIALIDADES                            0.975028
USO DE SUELO                                          0.978366
TRÁMITES / INFO MOVILIDAD                             0.981672
SOLICITUD Y MANTENIMIENTO DE ALERTA SÍSMICA           0.984912
INFORMACIÓN DE TRÁMITES                               0.987809
ASESORÍA Y CONSEJERÍA JURÍDICA Y LEGAL                0.990693
BALIZAMIENTO / REDUCTORES DE VELOCIDAD                0.993541
SOLICITUD DE PIPA DE AGUA                             0.996188
SOLICITUD Y MANTENIMIENTO DE CÁMARAS DE VIGILANCIA    0.998309
VENTA DE ALCOHOL / DROGA                              1.000000
Name: proportion, dtype: float64

In [149]:
X_train

,tipo_de_entrada,tema_solicitud,sexo,alcaldia_solicitud,codigo_postal_solicitud,dia_solicitud,mes_solicitud,hora_sin,hora_cos,tema_solicitud_compacto
574289,App CDMX,MANTENIMIENTO SEMÁFOROS,No especificado,Benito Juárez,03630,Thursday,April,-8.660254e-01,0.500000,MANTENIMIENTO SEMÁFOROS
1703317,Operador Telefónico LOCATEL,BACHEO,Masculino,Tlalpan,14220,Friday,August,1.224647e-16,-1.000000,BACHEO
469488,Interoperabilidad Iztapalapa,OTRO,Femenino,Iztapalapa,09850,Wednesday,September,-2.588190e-01,-0.965926,OTRO
1207310,App CDMX,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO,No especificado,Cuauhtémoc,06600,Thursday,January,-8.660254e-01,0.500000,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO
1730128,Operador Telefónico LOCATEL,MANTENIMIENTO DE COLADERA / ALCANTARILLA,No especificado,Iztapalapa,09100,Tuesday,September,-9.659258e-01,0.258819,MANTENIMIENTO DE COLADERA / ALCANTARILLA
...,...,...,...,...,...,...,...,...,...,...
274160,Portal Ciudadano SUAC,VEHÍCULO ABANDONADO / CHATARRIZACIÓN,No especificado,Gustavo A. Madero,07290,Tuesday,May,2.588190e-01,-0.965926,VEHÍCULO ABANDONADO / CHATARRIZACIÓN
1657313,Usuarios SUAC Dependencia,OTRO,No especificado,Iztacalco,08500,Monday,August,-5.000000e-01,-0.866025,OTRO
139863,Portal Ciudadano SUAC,PODA,No especificado,Azcapotzalco,02710,Monday,February,-9.659258e-01,0.258819,PODA
752862,Operador Telefónico LOCATEL,MANTENIMIENTO VÍA PÚBLICA,No especificado,Benito Juárez,03590,Sunday,September,2.588190e-01,-0.965926,MANTENIMIENTO VÍA PÚBLICA
129258,Interoperabilidad Miguel Hidalgo,OTRO,Masculino,Miguel Hidalgo,11850,Sunday,February,-8.660254e-01,-0.500000,OTRO

In [150]:
X_train.drop(columns=['tema_solicitud'],inplace=True)
X_train

,tipo_de_entrada,sexo,alcaldia_solicitud,codigo_postal_solicitud,dia_solicitud,mes_solicitud,hora_sin,hora_cos,tema_solicitud_compacto
574289,App CDMX,No especificado,Benito Juárez,03630,Thursday,April,-8.660254e-01,0.500000,MANTENIMIENTO SEMÁFOROS
1703317,Operador Telefónico LOCATEL,Masculino,Tlalpan,14220,Friday,August,1.224647e-16,-1.000000,BACHEO
469488,Interoperabilidad Iztapalapa,Femenino,Iztapalapa,09850,Wednesday,September,-2.588190e-01,-0.965926,OTRO
1207310,App CDMX,No especificado,Cuauhtémoc,06600,Thursday,January,-8.660254e-01,0.500000,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO
1730128,Operador Telefónico LOCATEL,No especificado,Iztapalapa,09100,Tuesday,September,-9.659258e-01,0.258819,MANTENIMIENTO DE COLADERA / ALCANTARILLA
...,...,...,...,...,...,...,...,...,...
274160,Portal Ciudadano SUAC,No especificado,Gustavo A. Madero,07290,Tuesday,May,2.588190e-01,-0.965926,VEHÍCULO ABANDONADO / CHATARRIZACIÓN
1657313,Usuarios SUAC Dependencia,No especificado,Iztacalco,08500,Monday,August,-5.000000e-01,-0.866025,OTRO
139863,Portal Ciudadano SUAC,No especificado,Azcapotzalco,02710,Monday,February,-9.659258e-01,0.258819,PODA
752862,Operador Telefónico LOCATEL,No especificado,Benito Juárez,03590,Sunday,September,2.588190e-01,-0.965926,MANTENIMIENTO VÍA PÚBLICA
129258,Interoperabilidad Miguel Hidalgo,Masculino,Miguel Hidalgo,11850,Sunday,February,-8.660254e-01,-0.500000,OTRO

In [151]:
X_train.info()

<class 'pandas.DataFrame'>
Index: 1500787 entries, 574289 to 129258
Data columns (total 9 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   tipo_de_entrada          1500787 non-null  str
 1   sexo                     1500787 non-null  str
 2   alcaldia_solicitud       1500787 non-null  str
 3   codigo_postal_solicitud  1500787 non-null  str
 4   dia_solicitud            1500787 non-null  str
 5   mes_solicitud            1500787 non-null  str
 6   hora_sin                 1500787 non-null  float64
 7   hora_cos                 1500787 non-null  float64
 8   tema_solicitud_compacto  1500787 non-null  str
dtypes: float64(2), str(7)
memory usage: 233.6 MB

In [152]:
X_test['tema_solicitud_compacto'] = X_test['tema_solicitud'].where(X_test['tema_solicitud'].isin(top_categorias),other='OTRO')

In [153]:
X_test.drop(columns=['tema_solicitud'],inplace=True)
X_test

,tipo_de_entrada,sexo,alcaldia_solicitud,codigo_postal_solicitud,dia_solicitud,mes_solicitud,hora_sin,hora_cos,tema_solicitud_compacto
221613,Portal Ciudadano SUAC,No especificado,Gustavo A. Madero,07740,Monday,April,-2.588190e-01,-0.965926,PODA
2198777,App CDMX,No especificado,Coyoacán,04600,Friday,March,-5.000000e-01,-0.866025,FUGA DE AGUA
1848480,Interoperabilidad SACMEX,No especificado,Benito Juárez,03400,Wednesday,October,-2.588190e-01,-0.965926,FALTA DE AGUA
2035005,Operador Telefónico LOCATEL,Femenino,Cuauhtémoc,06700,Tuesday,January,1.224647e-16,-1.000000,REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO
809955,Interoperabilidad Miguel Hidalgo,Masculino,Miguel Hidalgo,11490,Saturday,October,1.224647e-16,-1.000000,OTRO
...,...,...,...,...,...,...,...,...,...
542788,Interoperabilidad Iztapalapa,Femenino,Iztapalapa,09900,Wednesday,November,5.000000e-01,-0.866025,OTRO
1519643,Interoperabilidad SACMEX,No especificado,Iztapalapa,09830,Monday,June,5.000000e-01,-0.866025,FUGA DE AGUA
702295,Interoperabilidad Miguel Hidalgo,Masculino,Miguel Hidalgo,11000,Friday,August,2.588190e-01,-0.965926,MANTENIMIENTO VÍA PÚBLICA
258206,Usuarios SUAC Dependencia,Masculino,Azcapotzalco,02600,Thursday,May,-2.588190e-01,-0.965926,PAVIMENTACIÓN / REENCARPETADO
505921,Operador Telefónico LOCATEL,Femenino,Iztacalco,08100,Saturday,October,-9.659258e-01,-0.258819,PODA

In [154]:
X_test.info()

<class 'pandas.DataFrame'>
Index: 375197 entries, 221613 to 505921
Data columns (total 9 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   tipo_de_entrada          375197 non-null  str
 1   sexo                     375197 non-null  str
 2   alcaldia_solicitud       375197 non-null  str
 3   codigo_postal_solicitud  375197 non-null  str
 4   dia_solicitud            375197 non-null  str
 5   mes_solicitud            375197 non-null  str
 6   hora_sin                 375197 non-null  float64
 7   hora_cos                 375197 non-null  float64
 8   tema_solicitud_compacto  375197 non-null  str
dtypes: float64(2), str(7)
memory usage: 58.4 MB

In [155]:
columnas_ohe = ['tipo_de_entrada','sexo','alcaldia_solicitud','dia_solicitud','mes_solicitud','tema_solicitud_compacto']
ohe = OneHotEncoder(sparse_output=False)
for param in columnas_ohe:
    param_encoded = ohe.fit_transform(X_train[[param]])
    param_columns = ohe.get_feature_names_out([param])
    X_train[param_columns] = param_encoded
    X_train.drop(columns=[param],inplace=True)
    param_encoded_test = ohe.transform(X_test[[param]])
    X_test[param_columns] = param_encoded_test
    X_test.drop(columns=[param],inplace=True)
X_train
#entrada_encoded = ohe.fit_transform(X_train[['tipo_de_entrada']])
#entrada_columns = ohe.get_feature_names_out(['tipo_de_entrada'])
#X_train[entrada_columns] = entrada_encoded

,codigo_postal_solicitud,hora_sin,hora_cos,tipo_de_entrada_App CDMX,tipo_de_entrada_Interoperabilidad Iztapalapa,tipo_de_entrada_Interoperabilidad Miguel Hidalgo,tipo_de_entrada_Interoperabilidad SACMEX,tipo_de_entrada_Interoperabilidad Xochimilco,tipo_de_entrada_Operador Telefónico - Ventanilla,tipo_de_entrada_Operador Telefónico LOCATEL,...,"tema_solicitud_compacto_RETIRO CASCAJO, ESCOMBRO, AZOLVE, RAMAS",tema_solicitud_compacto_SOLICITUD DE PIPA DE AGUA,tema_solicitud_compacto_SOLICITUD DE VIGILANCIA POLICIACA,tema_solicitud_compacto_SOLICITUD Y MANTENIMIENTO DE ALERTA SÍSMICA,tema_solicitud_compacto_SOLICITUD Y MANTENIMIENTO DE CÁMARAS DE VIGILANCIA,tema_solicitud_compacto_TRÁMITES / INFO MOVILIDAD,tema_solicitud_compacto_USO DE SUELO,tema_solicitud_compacto_VEHÍCULO ABANDONADO / CHATARRIZACIÓN,tema_solicitud_compacto_VENTA DE ALCOHOL / DROGA,tema_solicitud_compacto_VERIFICACIÓN ADMINISTRATIVA
574289,03630,-8.660254e-01,0.500000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1703317,14220,1.224647e-16,-1.000000,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
469488,09850,-2.588190e-01,-0.965926,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1207310,06600,-8.660254e-01,0.500000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1730128,09100,-9.659258e-01,0.258819,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274160,07290,2.588190e-01,-0.965926,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1657313,08500,-5.000000e-01,-0.866025,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
139863,02710,-9.659258e-01,0.258819,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
752862,03590,2.588190e-01,-0.965926,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
129258,11850,-8.660254e-01,-0.500000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [156]:
X_train.info()

<class 'pandas.DataFrame'>
Index: 1500787 entries, 574289 to 129258
Data columns (total 87 columns):
 #   Column                                                                      Non-Null Count    Dtype
---  ------                                                                      --------------    -----
 0   codigo_postal_solicitud                                                     1500787 non-null  str
 1   hora_sin                                                                    1500787 non-null  float64
 2   hora_cos                                                                    1500787 non-null  float64
 3   tipo_de_entrada_App CDMX                                                    1500787 non-null  float64
 4   tipo_de_entrada_Interoperabilidad Iztapalapa                                1500787 non-null  float64
 5   tipo_de_entrada_Interoperabilidad Miguel Hidalgo                            1500787 non-null  float64
 6   tipo_de_entrada_Interoperabilidad SACMEX                                    1500787 non-null  float64
 7   tipo_de_entrada_Interoperabilidad Xochimilco                                1500787 non-null  float64
 8   tipo_de_entrada_Operador Telefónico - Ventanilla                            1500787 non-null  float64
 9   tipo_de_entrada_Operador Telefónico LOCATEL                                 1500787 non-null  float64
 10  tipo_de_entrada_Portal Ciudadano SUAC                                       1500787 non-null  float64
 11  tipo_de_entrada_Usuarios SUAC Dependencia                                   1500787 non-null  float64
 12  tipo_de_entrada_Whatsapp                                                    1500787 non-null  float64
 13  sexo_3                                                                      1500787 non-null  float64
 14  sexo_Femenino                                                               1500787 non-null  float64
 15  sexo_Masculino                                                              1500787 non-null  float64
 16  sexo_No especificado                                                        1500787 non-null  float64
 17  alcaldia_solicitud_Azcapotzalco                                             1500787 non-null  float64
 18  alcaldia_solicitud_Benito Juárez                                            1500787 non-null  float64
 19  alcaldia_solicitud_Coyoacán                                                 1500787 non-null  float64
 20  alcaldia_solicitud_Cuajimalpa de Morelos                                    1500787 non-null  float64
 21  alcaldia_solicitud_Cuauhtémoc                                               1500787 non-null  float64
 22  alcaldia_solicitud_Gustavo A. Madero                                        1500787 non-null  float64
 23  alcaldia_solicitud_Iztacalco                                                1500787 non-null  float64
 24  alcaldia_solicitud_Iztapalapa                                               1500787 non-null  float64
 25  alcaldia_solicitud_La Magdalena Contreras                                   1500787 non-null  float64
 26  alcaldia_solicitud_Miguel Hidalgo                                           1500787 non-null  float64
 27  alcaldia_solicitud_Milpa Alta                                               1500787 non-null  float64
 28  alcaldia_solicitud_Tlalpan                                                  1500787 non-null  float64
 29  alcaldia_solicitud_Tláhuac                                                  1500787 non-null  float64
 30  alcaldia_solicitud_Venustiano Carranza                                      1500787 non-null  float64
 31  alcaldia_solicitud_Xochimilco                                               1500787 non-null  float64
 32  alcaldia_solicitud_Álvaro Obregón                                           1500787 non-null  float64
 33  dia_solicitud_Friday                                                        1500787 non-null  float64
 34  dia_solicitud_Monday                                                        1500787 non-null  float64
 35  dia_solicitud_Saturday                                                      1500787 non-null  float64
 36  dia_solicitud_Sunday                                                        1500787 non-null  float64
 37  dia_solicitud_Thursday                                                      1500787 non-null  float64
 38  dia_solicitud_Tuesday                                                       1500787 non-null  float64
 39  dia_solicitud_Wednesday                                                     1500787 non-null  float64
 40  mes_solicitud_April                                                         1500787 non-null  float64
 41  mes_solicitud_August                                                        1500787 non-null  float64
 42  mes_solicitud_December                                                      1500787 non-null  float64
 43  mes_solicitud_February                                                      1500787 non-null  float64
 44  mes_solicitud_January                                                       1500787 non-null  float64
 45  mes_solicitud_July                                                          1500787 non-null  float64
 46  mes_solicitud_June                                                          1500787 non-null  float64
 47  mes_solicitud_March                                                         1500787 non-null  float64
 48  mes_solicitud_May                                                           1500787 non-null  float64
 49  mes_solicitud_November                                                      1500787 non-null  float64
 50  mes_solicitud_October                                                       1500787 non-null  float64
 51  mes_solicitud_September                                                     1500787 non-null  float64
 52  tema_solicitud_compacto_ASESORÍA Y CONSEJERÍA JURÍDICA Y LEGAL              1500787 non-null  float64
 53  tema_solicitud_compacto_BACHEO                                              1500787 non-null  float64
 54  tema_solicitud_compacto_BALIZAMIENTO / REDUCTORES DE VELOCIDAD              1500787 non-null  float64
 55  tema_solicitud_compacto_BARBECHO / CHAPONEO                                 1500787 non-null  float64
 56  tema_solicitud_compacto_DESAZOLVE                                           1500787 non-null  float64
 57  tema_solicitud_compacto_FALTA DE AGUA                                       1500787 non-null  float64
 58  tema_solicitud_compacto_FUGA DE AGUA                                        1500787 non-null  float64
 59  tema_solicitud_compacto_INFORMACIÓN DE TRÁMITES                             1500787 non-null  float64
 60  tema_solicitud_compacto_LIMPIEZA VÍA PÚBLICA                                1500787 non-null  float64
 61  tema_solicitud_compacto_MANTENIMIENTO DE BANQUETAS                          1500787 non-null  float64
 62  tema_solicitud_compacto_MANTENIMIENTO DE COLADERA / ALCANTARILLA            1500787 non-null  float64
 63  tema_solicitud_compacto_MANTENIMIENTO DRENAJE                               1500787 non-null  float64
 64  tema_solicitud_compacto_MANTENIMIENTO PARQUE / ÁREA VERDE                   1500787 non-null  float64
 65  tema_solicitud_compacto_MANTENIMIENTO SEMÁFOROS                             1500787 non-null  float64
 66  tema_solicitud_compacto_MANTENIMIENTO VÍA PÚBLICA                           1500787 non-null  float64
 67  tema_solicitud_compacto_OTRO                                                1500787 non-null  float64
 68  tema_solicitud_compacto_PAVIMENTACIÓN / REENCARPETADO                       1500787 non-null  float64
 69  tema_solicitud_compacto_PODA                                                1500787 non-null  float64
 70  tema_solicitud_compacto_PROTECCIÓN CIVIL                                    1500787 non-null  float64
 71  tema_solicitud_compacto_QUEJA DE TRANSPORTE PÚBLICO                         1500787 non-null  float64
 72  tema_solicitud_compacto_QUEJA SERVIDOR PÚBLICO                              1500787 non-null  float64
 73  tema_solicitud_compacto_RECOLECCIÓN BASURA                                  1500787 non-null  float64
 74  tema_solicitud_compacto_RECUPERACIÓN DE VIALIDADES                          1500787 non-null  float64
 75  tema_solicitud_compacto_REPARACIÓN Y MANTENIMIENTO DE ALUMBRADO PÚBLICO     1500787 non-null  float64
 76  tema_solicitud_compacto_RETIRO AMBULANTE                                    1500787 non-null  float64
 77  tema_solicitud_compacto_RETIRO CASCAJO, ESCOMBRO, AZOLVE, RAMAS             1500787 non-null  float64
 78  tema_solicitud_compacto_SOLICITUD DE PIPA DE AGUA                           1500787 non-null  float64
 79  tema_solicitud_compacto_SOLICITUD DE VIGILANCIA POLICIACA                   1500787 non-null  float64
 80  tema_solicitud_compacto_SOLICITUD Y MANTENIMIENTO DE ALERTA SÍSMICA         1500787 non-null  float64
 81  tema_solicitud_compacto_SOLICITUD Y MANTENIMIENTO DE CÁMARAS DE VIGILANCIA  1500787 non-null  float64
 82  tema_solicitud_compacto_TRÁMITES / INFO MOVILIDAD                           1500787 non-null  float64
 83  tema_solicitud_compacto_USO DE SUELO                                        1500787 non-null  float64
 84  tema_solicitud_compacto_VEHÍCULO ABANDONADO / CHATARRIZACIÓN                1500787 non-null  float64
 85  tema_solicitud_compacto_VENTA DE ALCOHOL / DROGA                            1500787 non-null  float64
 86  tema_solicitud_compacto_VERIFICACIÓN ADMINISTRATIVA                         1500787 non-null  float64
dtypes: float64(86), str(1)
memory usage: 1014.9 MB

In [157]:
y_train.isnull().mean()*100

np.float64(0.0)

In [158]:
target_encode = TargetEncoder()
zc_encoded = target_encode.fit_transform(X_train[['codigo_postal_solicitud']],y_train)
X_train['zc_encoded'] = zc_encoded
X_train.drop(columns=['codigo_postal_solicitud'],inplace=True)
X_train

KeyboardInterrupt:

In [ ]:
X_train.info()

In [ ]:
zc_encoded_test = target_encode.transform(X_test[['codigo_postal_solicitud']])
X_test['zc_encoded'] = zc_encoded_test
X_test.drop(columns=['codigo_postal_solicitud'],inplace=True)

In [ ]:
X_test.info()

## Transformaciones

### Entrenamiento

### Testeo